title: 0xProto
url: https://github.com/0xType/0xProto

tags: Monospace, Coding

fontauthor: 0xType
fontyear: 2023

heroletter: 0x
heroword: "0xFF"
color: steelblue

content: |
  0xProto ist eine junge Coding-Schrift mit klarem technischen Charakter und durchdachter Unterscheidbarkeit ähnlich aussehender Zeichen (0/O, l/1/I). Optionale Ligaturen lassen sich aktivieren oder deaktivieren, ohne den Zeichenfluss zu unterbrechen. Ein eigenständiger Beitrag zu einer Gattung, die von etablierten Namen dominiert wird.
