title: Mozilla Text
url: https://github.com/mozilla/mozilla-type-family

tags: Slab Serif, Humanist Sans

comment: "Need to slab on a header? There you go."

fontauthor: Studio DRAMA
fontyear: 2024

heroletter: Aá
heroword: Readme
herostyle:
color: darkorange
