title: Mozilla Text
url: https://github.com/mozilla/mozilla-type-family

tags: Sans, Slab Serif, Humanist Sans

comment: "Brauchst du eine Serifenschrift für Überschriften? Bitteschön."

fontauthor: Studio DRAMA
fontyear: 2024

heroletter: Aá
heroword: Readme
herostyle:
color: darkorange
