title: Victor Mono
url: https://rubjo.github.io/victor-mono/
wikipedia:

tags: Monospace, Coding

fontauthor: Rune Bjørnerås
fontyear: 2019

heroletter: Vv
heroword: Victor
color: steelblue
border: lines.svg

content: |
  Victor Mono ist eine kostenlose Programmierschrift mit optionalen
  kursiven Schreibschrift-Ligaturen und Ligatur-Unterstützung für
  häufige Programmiersymbole. Besonders markant: die kursiven
  Glyphen sind als echte Schreibschrift gestaltet.
