title: Unifraktur
url: https://unifraktur.sourceforge.net/
comment:

tags: Blackletter, Script, Display

fontauthor:  j-mach-wust, wrzlprmft, Carl Albert Fahrenwaldt (1901)
fontyear: 2010

heroletter: Aa
heroword: Medival
herostyle:

border: floral.svg
wikipedia: "https://de.wikipedia.org/wiki/Fraktur_(Schrift)"
