title: Unifraktur
url: https://unifraktur.sourceforge.net/
comment:

tags: Script, Display

fontauthor:  j-mach-wust, wrzlprmft, Carl Albert Fahrenwaldt (1901)
fontyear: 2010

heroletter: Aa
heroword: Medival
herostyle:
color: maroon
