title: Tangerine
url: https://github.com/googlefonts/TangerineFont

tags: Script, Kalligraphisch

fontauthor: Toshi Omagari
fontyear: 2008

heroletter: Tt
heroword: "Tangerine"
color: purple

content: |
  Tangerine ist eine elegante, feingliedrige Spitzfeder-Kalligrafie mit hauchzarten Strichen und zeitloser Anmut. Die feinen Linien und die kontrollierte Modulation verleihen ihr eine klassische Schreibschrift-Ästhetik, die sich von den informelleren Handschriften im Bestand unterscheidet. Sie ergänzt die Sammlung um eine klassische Spitzfeder-Hand — mit nur 232 Glyphen allerdings ohne erweiterten Zeichensatz.
