title: Nunito
url: https://github.com/googlefonts/NunitoSans
tags: Sans, Geometric, Rounded
fontauthor: Vernon Adams, Cyreal
fontyear: 2014
heroletter: No
heroword: Rund

border: dots.svg

content: |
  Nunito von Vernon Adams ist eine geometrische Groteskschrift mit durchgehend abgerundeten Endstrichen, die ihr einen freundlichen, zugänglichen Charakter verleihen. Die weichen Formen machen sie zur beliebten Wahl für Kinder-Apps, UI-Designs und Marken, die Zugänglichkeit und Wärme kommunizieren wollen.
