title: Chivo
url: https://fonts.google.com/specimen/Chivo

tags: Sans, Humanist

fontauthor: Héctor Gatti, Omnibus Type
fontyear: 2013

heroletter: Ch
heroword: "Chivo"
color: sienna

content: |
  Chivo (spanisch: «Ziegenbock») von Héctor Gatti und Omnibus Type ist ein humanistischer Grotesque mit leicht unregelmäßigen, handwerklichen Zügen. Die Schrift wurde ursprünglich für argentinische Printmedien entworfen und trägt diese Herkunft im Text: etwas rauer als Inter, persönlicher als Lato. Variable Font seit der Neuauflage 2022.
