title: Tex Gyre Bonum
url: https://www.gust.org.pl/projects/e-foundry/tex-gyre
wikipedia: https://en.wikipedia.org/wiki/Bookman_(typeface)

tags: Serif, Garalde, Slab Serif

comment: "TeX Gyre Bonum kann als Ersatz für ITC Bookman verwendet werden (entworfen von Alexander Phemister, 1860, überarbeitet von Edward Benguiat, 1975)."

fontauthor: Bogusław Jackowski, Janusz M. Nowacki, Piotr Strzelczyk
fontyear: 2006

heroletter: Aa
heroword: Book
herostyle:

