title: Tex Gyre Adventor
url: https://www.gust.org.pl/projects/e-foundry/tex-gyre
wikipedia: https://en.wikipedia.org/wiki/ITC_Avant_Garde

tags: Geometric Grotesk

comment: "TeX Gyre Adventor kann als Ersatz für ITC Avant Garde Gothic verwendet werden (entworfen von Herb Lubalin und Tom Carnase, 1970)."

fontauthor: Bogusław Jackowski, Janusz M. Nowacki, Piotr Strzelczyk
fontyear: 2006

heroletter: Aa
heroword: Avant Garde
herostyle:
color: goldenrod

imageOverrides:
  "ArcRaiders_KeyArt_Main_1-1_2160x2160.png)":
    alt: "Embark Studios Press Kit (via fontsinuse.com)"
    source: "https://www.embark-studios.com/press"