title: Playfair
url: https://www.forthehearts.net/playfair

tags: Serif, Humanist

comment:

fontauthor: Claus Eggers Sørensen
fontyear: 2023

heroletter: Aa
heroword: Fairy
herostyle:

border: doodle.svg