title: Commit Mono
url: https://commitmono.com/
tags: Monospace, Coding, Neutral
fontauthor: Eigil Nikolajsen
fontyear: 2023
heroletter: Cc
heroword: Commit
color: olivedrab
border: lines_thin.svg
content: |
  Bewusst neutrale Coding-Monospace mit dem Ziel, Ablenkung zu
  minimieren. Jede Designentscheidung folgt dem Prinzip: nur was
  der Lesbarkeit dient. Keine Ligaturen, klare Unterscheidbarkeit
  aller Glyphen (0/O, 1/l/I).
