title: Recursive
url: https://www.recursive.design

tags: Monospace, Sans, Variable

fontauthor: Arrow Type (Stephen Nixon)
fontyear: 2020

heroletter: Rr
heroword: Recursion
herostyle: bold
color: mediumorchid

content: |
  Recursive ist eine außergewöhnliche variable Schrift, die mit einer einzigen Fontdatei das gesamte Spektrum von Monospace über Sans bis zu einem Casual-Brush-Stil abdeckt. Die MONO-Achse ermöglicht den fließenden Übergang zwischen proportional und monospaced, während CASL und wght gemeinsam die Persönlichkeit regeln. Entworfen von Arrow Type für Code und Fließtext gleichermaßen.
