"""
font_specimen_svg_generator.py
generated by Claude AI

Font Specimen SVG Generator
============================
Analog zu font_specimen_generator.py — gibt SVGs statt PNGs aus.

Durchsucht einen Ordner nach Schriftdateien (.ttf, .otf, .woff, .woff2)
und erstellt für jede Schriftfamilie eine Vorschau als selbst-enthaltende SVG
(Schrift als Base64 eingebettet, keine externen Abhängigkeiten zur Laufzeit).

Layout (angelehnt an Wikipedia-Fontspecimen):
  Oberer Bereich  — Fontname, "Aa Ee Rr" Regular + Italic, Heroword, Ghost-Buchstabe
  Unterer Bereich — Kleinbuchstaben-Alphabet (gespact), Ziffern Regular

Benötigte Bibliotheken:
    pip install fonttools brotli

Verwendung:
    python font_specimen_svg_generator.py --input ./fonts --output ./previews
    python font_specimen_svg_generator.py --input ./fonts --output ./previews --theme white
    python font_specimen_svg_generator.py --input ./fonts --output ./previews --width 1400 --theme cream
    python font_specimen_svg_generator.py --input ./fonts --output ./previews --overwrite
    python font_specimen_svg_generator.py --input ./fonts --output ./previews --wordlist ./woerter.txt
"""

import argparse
import base64
import colorsys
import html as _html
import os
import random
import re
import sys
from pathlib import Path

try:
    from fontTools.ttLib import TTFont
except ImportError:
    print("Fehler: fonttools nicht installiert. Bitte 'pip install fonttools brotli' ausführen.")
    sys.exit(1)


# ── Farbpaletten (identisch mit font_specimen_generator.py) ───────────────────

THEMES = {
    "dark": {
        "upper_bg":   "#1e2035",
        "lower_bg":   "#12141f",
        "accent":     "#b4d273",
        "text":       "#eaeaea",
        "name_color": "#55577a",
        "ghost":      "#252848",
        "lower_text": "#dde0f0",
    },
    "white": {
        "upper_bg":   "#e8e4dc",
        "lower_bg":   "#c8c0a8",
        "accent":     "#7a5c10",
        "text":       "#1a1208",
        "name_color": "#9a9080",
        "ghost":      "#f5f2ec",
        "lower_text": "#faf8f4",
    },
    "cream": {
        "upper_bg":   "#c5baa0",
        "lower_bg":   "#b89354",
        "accent":     "#c8a020",
        "text":       "#1a1208",
        "name_color": "#8a8070",
        "ghost":      "#ddd5c0",
        "lower_text": "#ffffff",
    },
}


def generate_random_theme() -> dict:
    """Leitet harmonische Farben aus einem zufälligen Grundton ab."""
    h = random.random()
    h_accent = (h + random.choice([0.33, 0.38, 0.42, 0.58, 0.62, 0.67])) % 1.0
    mode = random.choice(["dark", "light", "mid"])

    def hls(hue: float, lightness: float, saturation: float) -> str:
        r, g, b = colorsys.hls_to_rgb(hue % 1.0, lightness, saturation)
        return f"#{int(r * 255):02x}{int(g * 255):02x}{int(b * 255):02x}"

    if mode == "dark":
        return {
            "upper_bg":   hls(h,        0.11, 0.28),
            "lower_bg":   hls(h,        0.07, 0.22),
            "accent":     hls(h_accent, 0.65, 0.80),
            "text":       hls(h,        0.91, 0.12),
            "name_color": hls(h,        0.36, 0.28),
            "ghost":      hls(h,        0.16, 0.24),
            "lower_text": hls(h,        0.88, 0.15),
        }
    elif mode == "light":
        return {
            "upper_bg":   hls(h,        0.91, 0.20),
            "lower_bg":   hls(h,        0.80, 0.28),
            "accent":     hls(h_accent, 0.32, 0.72),
            "text":       hls(h,        0.09, 0.28),
            "name_color": hls(h,        0.60, 0.20),
            "ghost":      hls(h,        0.96, 0.16),
            "lower_text": hls(h,        0.07, 0.22),
        }
    else:  # mid
        return {
            "upper_bg":   hls(h,        0.68, 0.42),
            "lower_bg":   hls(h,        0.54, 0.52),
            "accent":     hls(h_accent, 0.20, 0.70),
            "text":       hls(h,        0.06, 0.30),
            "name_color": hls(h,        0.45, 0.32),
            "ghost":      hls(h,        0.80, 0.35),
            "lower_text": hls(h,        0.96, 0.12),
        }


# ── Dateinamen-Parsing (identisch mit font_specimen_generator.py) ─────────────

_SUBFAMILY_RE = re.compile(
    r"^(?:"
    r"(thin|extralight|ultralight|light|regular|book|normal|medium|"
    r"semibold|demibold|bold|extrabold|ultrabold|black|heavy|variable|vf)"
    r"(italic|oblique)?"
    r"|(\[?ital\]?|italic|oblique)"
    r")$",
    re.IGNORECASE,
)


def _strip_axes(s: str) -> str:
    return re.sub(r"[\[\(][^\]\)]*[\]\)]", "", s).rstrip("-_ ")


def _parse_name_from_filename(stem: str) -> tuple[str, str]:
    clean = _strip_axes(stem)
    for sep in ("-", "_"):
        if sep in clean:
            idx = clean.rfind(sep)
            suffix = clean[idx + 1:]
            if _SUBFAMILY_RE.match(suffix):
                return clean[:idx], suffix
    return clean, ""


def get_font_name(font_path: str) -> tuple[str, str]:
    try:
        tt = TTFont(font_path)
        name_table = tt["name"]

        def get_name(name_id):
            for record in name_table.names:
                if record.nameID == name_id:
                    try:
                        return record.toUnicode()
                    except Exception:
                        return record.string.decode("latin-1", errors="replace")
            return ""

        family = get_name(1) or Path(font_path).stem
        sub    = get_name(2) or ""
        pf     = get_name(16)
        ps     = get_name(17)
        if pf:
            family = pf
        if ps:
            sub = ps
        return family.strip(), sub.strip()
    except Exception:
        return _parse_name_from_filename(Path(font_path).stem)


def classify_subfamily(subfamily: str) -> str:
    s = subfamily.strip().lower().replace(" ", "").replace("-", "").replace("_", "")
    if s in ("", "regular", "roman", "book", "normal", "upright", "variable", "vf"):
        return "regular"
    if s in ("italic", "regularitalic", "oblique", "regularoblique",
             "variableitalic", "vfitalic"):
        return "italic"
    return "other"


def group_fonts_by_family(font_paths: list[str]) -> dict:
    groups: dict[str, dict] = {}
    for path in font_paths:
        family, subfamily = get_font_name(path)
        kind = classify_subfamily(subfamily)
        if kind == "other":
            continue
        if family not in groups:
            groups[family] = {"regular": None, "italic": None}
        if groups[family][kind] is None:
            groups[family][kind] = path
    return groups


def load_wordlist(wordlist_path: str) -> list[str]:
    try:
        with open(wordlist_path, encoding="utf-8") as f:
            words = [line.strip() for line in f if line.strip()]
        return words if words else ["Hamburgefonstiv"]
    except FileNotFoundError:
        print(f"  Hinweis: Wortliste '{wordlist_path}' nicht gefunden — Fallback wird verwendet.")
        return ["Hamburgefonstiv"]


def slugify(name: str) -> str:
    return "".join(c if c.isalnum() or c in "-_" else "_" for c in name)


# ── Font-Einbettung ───────────────────────────────────────────────────────────

def font_to_data_uri(font_path: str) -> tuple[str, str]:
    """Gibt (data_uri, css_format_hint) für die Verwendung in @font-face zurück."""
    ext = Path(font_path).suffix.lower()
    mime_map = {
        ".woff2": ("font/woff2",     "woff2"),
        ".woff":  ("font/woff",      "woff"),
        ".otf":   ("font/otf",       "opentype"),
        ".ttf":   ("font/truetype",  "truetype"),
    }
    mime, fmt = mime_map.get(ext, ("font/truetype", "truetype"))
    with open(font_path, "rb") as f:
        b64 = base64.b64encode(f.read()).decode("ascii")
    return f"data:{mime};base64,{b64}", fmt


# ── fonttools Metriken ────────────────────────────────────────────────────────

def _upem(tt: TTFont) -> int:
    return tt["head"].unitsPerEm


def _ascender(tt: TTFont) -> int:
    os2 = tt.get("OS/2")
    return os2.sTypoAscender if os2 else tt["hhea"].ascent


def _cap_height(tt: TTFont) -> int:
    os2 = tt.get("OS/2")
    if os2 and getattr(os2, "sCapHeight", 0):
        return os2.sCapHeight
    return int(_ascender(tt) * 0.72)


def text_height(tt: TTFont, size: float) -> float:
    """Sichtbare Höhe einer Großbuchstabenzeile (≈ Cap-Height)."""
    return _cap_height(tt) * size / _upem(tt)


def baseline_offset(tt: TTFont, size: float) -> float:
    """Abstand von der Oberkante der Textzeile zur Baseline."""
    return _ascender(tt) * size / _upem(tt)


def text_width(text: str, tt: TTFont, size: float) -> float:
    """Approximierte Textbreite über Vorschubbreiten aus hmtx."""
    cmap  = tt.getBestCmap() or {}
    hmtx  = tt["hmtx"].metrics
    upem  = _upem(tt)
    total = 0.0
    for ch in text:
        gname = cmap.get(ord(ch))
        total += hmtx[gname][0] if gname and gname in hmtx else upem * 0.5
    return total * size / upem


def lsb_of_char(ch: str, tt: TTFont, size: float) -> float:
    """Left Side Bearing eines einzelnen Zeichens in Pixeln."""
    cmap  = tt.getBestCmap() or {}
    hmtx  = tt["hmtx"].metrics
    upem  = _upem(tt)
    gname = cmap.get(ord(ch))
    lsb   = hmtx[gname][1] if gname and gname in hmtx else 0
    return lsb * size / upem


# ── SVG-Hilfsfunktionen ───────────────────────────────────────────────────────

def _x(s) -> str:
    return _html.escape(str(s), quote=True)


def _css_family(name: str) -> str:
    """Gibt den Font-Family-Namen CSS-sicher in einfachen Anführungszeichen zurück."""
    return "'" + name.replace("\\", "\\\\").replace("'", "\\'") + "'"


def _text(x, y, content, family, size, color, style="normal"):
    css = (
        f"font-family: {_css_family(family)}; "
        f"font-size: {size}px; "
        f"fill: {color}; "
        f"font-style: {style};"
    )
    return f'  <text x="{x:.1f}" y="{y:.1f}" style="{css}">{_x(content)}</text>'


# ── SVG-Specimen-Generierung ──────────────────────────────────────────────────

def draw_specimen_svg(
    regular_path: str,
    output_path: str,
    italic_path: str | None = None,
    heroword: str = "Hamburgefonstiv",
    canvas_width: int = 1000,
    theme_name: str = "dark",
) -> None:

    C   = generate_random_theme() if theme_name == "random" else THEMES[theme_name]
    PAD = int(canvas_width * 0.10)

    family, _ = get_font_name(regular_path)

    tt_r = TTFont(regular_path)
    tt_i = TTFont(italic_path) if italic_path else None

    # ── Schriftgrößen (analog PNG-Version) ────────────────────────────────────
    sz_demo  = int(canvas_width * 0.115)
    sz_hero  = int(canvas_width * 0.090)
    sz_ghost = int(canvas_width * 0.520)
    sz_digit = int(canvas_width * 0.068)

    # Fontname: Größe dynamisch so wählen, dass Name die volle Breite ausfüllt
    _ref_sz   = int(canvas_width * 0.14)
    _name_tgt = canvas_width - 2 * PAD
    _ref_w    = text_width(family, tt_r, _ref_sz)
    name_sz   = int(_ref_sz * _name_tgt / max(_ref_w, 1))
    name_sz   = max(min(name_sz, int(canvas_width * 0.42)), int(canvas_width * 0.05))

    # Alphabet-Größe: begrenzen, damit Zeile nicht überläuft
    alpha1     = " ".join("abcdefghijklm")
    alpha2     = " ".join("nopqrstuvwxyz")
    digits_str = " ".join("1234567890")
    _alpha_max = int(canvas_width * 0.075)
    _alpha_w   = text_width(alpha1, tt_r, _alpha_max)
    sz_alpha   = max(20, int(_alpha_max * _name_tgt / _alpha_w)) if _alpha_w > _name_tgt else _alpha_max

    # ── Höhen berechnen (analog PNG-Version) ──────────────────────────────────
    LINE_S = int(canvas_width * 0.022)
    LINE_M = int(canvas_width * 0.038)
    LINE_L = int(canvas_width * 0.052)

    name_h   = text_height(tt_r,          name_sz)
    demo_r_h = text_height(tt_r,          sz_demo)
    demo_i_h = text_height(tt_i,          sz_demo) if tt_i else 0
    hero_h   = text_height(tt_i or tt_r,  sz_hero)
    alpha_h  = text_height(tt_r,          sz_alpha)
    digit_h  = text_height(tt_r,          sz_digit)

    upper_h = int(
        PAD
        + name_h + LINE_L
        + demo_r_h + LINE_S
        + ((demo_i_h + LINE_M) if tt_i else 0)
        + hero_h
        + PAD
    )
    lower_h = int(
        PAD
        + alpha_h + int(LINE_S * 0.8)
        + alpha_h + LINE_M
        + digit_h
        + PAD
    )
    canvas_height = upper_h + lower_h

    # ── @font-face CSS ────────────────────────────────────────────────────────
    r_uri, r_fmt = font_to_data_uri(regular_path)
    font_css  = (
        f'@font-face {{\n'
        f'  font-family: {_css_family(family)};\n'
        f'  font-style: normal;\n'
        f'  src: url("{r_uri}") format("{r_fmt}");\n'
        f'}}\n'
    )
    if italic_path:
        i_uri, i_fmt = font_to_data_uri(italic_path)
        font_css += (
            f'@font-face {{\n'
            f'  font-family: {_css_family(family)};\n'
            f'  font-style: italic;\n'
            f'  src: url("{i_uri}") format("{i_fmt}");\n'
            f'}}\n'
        )

    # ── SVG zusammenbauen ─────────────────────────────────────────────────────
    out = []
    out.append('<?xml version="1.0" encoding="UTF-8"?>')
    out.append(
        f'<svg xmlns="http://www.w3.org/2000/svg"'
        f' width="{canvas_width}" height="{canvas_height}"'
        f' viewBox="0 0 {canvas_width} {canvas_height}">'
    )

    # Eingebettete Schrift
    out.append('  <defs>')
    out.append('    <style><![CDATA[')
    out.append(font_css)
    out.append('    ]]></style>')
    out.append('  </defs>')

    # Hintergründe
    out.append(f'  <rect width="{canvas_width}" height="{upper_h}" fill="{C["upper_bg"]}"/>')
    out.append(f'  <rect y="{upper_h}" width="{canvas_width}" height="{lower_h}" fill="{C["lower_bg"]}"/>')

    # Ghost-Buchstabe (zuerst → liegt hinter dem Fließtext)
    demo_end = PAD + max(
        text_width("Aa Ee Rr", tt_r, sz_demo),
        text_width("Aa Ee Rr", tt_i, sz_demo) if tt_i else 0,
    )
    ghost_lsb = lsb_of_char("A", tt_r, sz_ghost)
    ghost_x   = demo_end + int(canvas_width * 0.02) - ghost_lsb
    ghost_y   = PAD + name_h + baseline_offset(tt_r, sz_ghost)
    out.append(_text(ghost_x, ghost_y, "Aa", family, sz_ghost, C["ghost"]))

    # ── Oberer Bereich ────────────────────────────────────────────────────────
    y = PAD

    # Fontname
    out.append(_text(PAD, y + baseline_offset(tt_r, name_sz), family, family, name_sz, C["name_color"]))
    y += name_h + LINE_L

    # "Aa Ee Rr" Regular
    out.append(_text(PAD, y + baseline_offset(tt_r, sz_demo), "Aa Ee Rr", family, sz_demo, C["text"]))
    y += demo_r_h + LINE_S

    # "Aa Ee Rr" Italic (nur wenn Italic-Schnitt vorhanden)
    if tt_i:
        out.append(_text(PAD, y + baseline_offset(tt_i, sz_demo), "Aa Ee Rr", family, sz_demo, C["text"], "italic"))
        y += demo_i_h + LINE_M

    # Heroword in Akzentfarbe
    tt_h     = tt_i if tt_i else tt_r
    hero_sty = "italic" if tt_i else "normal"
    out.append(_text(PAD, y + baseline_offset(tt_h, sz_hero), heroword, family, sz_hero, C["accent"], hero_sty))

    # ── Unterer Bereich ───────────────────────────────────────────────────────
    y = upper_h + PAD

    out.append(_text(PAD, y + baseline_offset(tt_r, sz_alpha), alpha1, family, sz_alpha, C["lower_text"]))
    y += alpha_h + int(LINE_S * 0.8)

    out.append(_text(PAD, y + baseline_offset(tt_r, sz_alpha), alpha2, family, sz_alpha, C["lower_text"]))
    y += alpha_h + LINE_M

    # Ziffern: rechtsbündig
    digit_w = text_width(digits_str, tt_r, sz_digit)
    digit_x = canvas_width - PAD - digit_w
    out.append(_text(digit_x, y + baseline_offset(tt_r, sz_digit), digits_str, family, sz_digit, C["lower_text"]))

    out.append('</svg>')

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
        f.write("\n")

    italic_info = " + Italic" if italic_path else ""
    print(f"  ✓  {Path(output_path).name}  [{canvas_width}×{canvas_height}px]  ({family}{italic_info})")


# ── Ordner-Scan & Batch-Verarbeitung ─────────────────────────────────────────

FONT_EXTENSIONS = {".ttf", ".otf", ".woff", ".woff2"}


def find_fonts(folder: str) -> list[str]:
    found = []
    for root, _, files in os.walk(folder):
        for f in sorted(files):
            if Path(f).suffix.lower() in FONT_EXTENSIONS:
                found.append(os.path.join(root, f))
    return found


def process_folder(
    input_folder: str,
    output_folder: str,
    width: int = 1000,
    theme: str = "dark",
    overwrite: bool = False,
    wordlist_path: str | None = None,
) -> None:

    os.makedirs(output_folder, exist_ok=True)
    all_fonts = find_fonts(input_folder)

    if not all_fonts:
        print(f"Keine Schriftdateien in '{input_folder}' gefunden.")
        print(f"Unterstützte Formate: {', '.join(sorted(FONT_EXTENSIONS))}")
        return

    families              = group_fonts_by_family(all_fonts)
    families_with_regular = {k: v for k, v in families.items() if v["regular"]}
    skipped_no_regular    = len(families) - len(families_with_regular)

    default_wordlist = Path(__file__).parent / "wordlist.txt"
    words = load_wordlist(str(wordlist_path) if wordlist_path else str(default_wordlist))

    print(f"\nFont Specimen SVG Generator")
    print(f"{'─' * 50}")
    print(f"Eingabe:  {input_folder}")
    print(f"Ausgabe:  {output_folder}")
    print(f"Breite:   {width}px   Theme: {theme}")
    print(
        f"Dateien gefunden: {len(all_fonts)}  →  Familien: {len(families_with_regular)}"
        + (f"  ({skipped_no_regular} ohne Regular übersprungen)" if skipped_no_regular else "")
    )
    print(f"{'─' * 50}\n")

    ok = skip = err = 0

    for family, cuts in families_with_regular.items():
        regular_path = cuts["regular"]
        italic_path  = cuts["italic"]
        safe_name    = slugify(family)
        out_name     = f"{safe_name}.svg"
        out_path     = os.path.join(output_folder, out_name)

        if not overwrite and os.path.exists(out_path):
            print(f"  –  {out_name}  (übersprungen, bereits vorhanden)")
            skip += 1
            continue

        heroword = random.choice(words)

        try:
            draw_specimen_svg(
                regular_path=regular_path,
                output_path=out_path,
                italic_path=italic_path,
                heroword=heroword,
                canvas_width=width,
                theme_name=theme,
            )
            ok += 1
        except Exception as e:
            print(f"  ✗  {family}  →  Fehler: {e}")
            err += 1

    print(f"\n{'─' * 50}")
    print(f"Fertig!  ✓ {ok} erstellt   – {skip} übersprungen   ✗ {err} Fehler")
    print(f"Vorschauen in: {os.path.abspath(output_folder)}\n")


# ── Einstiegspunkt ────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generiert Font-Specimen-SVGs für alle Schriftfamilien in einem Ordner.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Beispiele:
  python font_specimen_svg_generator.py --input ./fonts --output ./previews
  python font_specimen_svg_generator.py --input ./fonts --output ./previews --theme white
  python font_specimen_svg_generator.py --input ./fonts --output ./previews --width 1400 --theme cream
  python font_specimen_svg_generator.py --input ./fonts --output ./previews --overwrite
  python font_specimen_svg_generator.py --input ./fonts --output ./previews --wordlist ./woerter.txt
        """,
    )
    parser.add_argument("--input",    "-i", required=True,
                        help="Ordner mit Schriftdateien (wird rekursiv durchsucht)")
    parser.add_argument("--output",   "-o", required=True,
                        help="Ausgabeordner für die SVG-Vorschauen")
    parser.add_argument("--width",    "-w", type=int, default=1000,
                        help="Breite der Vorschaubilder in Pixel (Standard: 1000)")
    parser.add_argument("--theme",    "-t", default="dark",
                        choices=list(THEMES.keys()) + ["random"],
                        help="Farbschema: dark | white | cream | random (Standard: dark)")
    parser.add_argument("--wordlist", default=None,
                        help="Pfad zur Wortliste (Standard: wordlist.txt neben dem Script)")
    parser.add_argument("--overwrite", action="store_true",
                        help="Bereits vorhandene Vorschauen überschreiben")

    args = parser.parse_args()

    if args.width < 400:
        print("Fehler: Mindestbreite ist 400px.")
        sys.exit(1)

    process_folder(
        input_folder  = args.input,
        output_folder = args.output,
        width         = args.width,
        theme         = args.theme,
        overwrite     = args.overwrite,
        wordlist_path = args.wordlist,
    )


if __name__ == "__main__":
    main()
