"""
generate_font_specimens.py
generated by Claude Ai

Font Specimen Generator
=======================
Durchsucht einen Ordner nach Schriftdateien (.ttf, .otf, .woff, .woff2)
und erstellt für jede Schriftfamilie eine Vorschau im Stil der Wikipedia Font Specimens.
Berücksichtigt nur Regular und Regular Italic — andere Schnitte (Bold, Light …) werden ignoriert.

Layout (angelehnt an Wikipedia-Fontspecimen):
  Oberer Bereich  — Fontname, "Aa Ee Rr" Regular + Italic, Heroword, Ghost-Buchstabe
  Unterer Bereich — Kleinbuchstaben-Alphabet (gespact), Ziffern Regular + Italic

Benötigte Bibliotheken:
    pip install Pillow fonttools brotli

Verwendung:
    python font_specimen_generator.py --input ./fonts --output ./previews
    python font_specimen_generator.py --input ./fonts --output ./previews --width 1200 --theme cream
"""

import argparse
import colorsys
import io
import os
import re
import random
import sys
from pathlib import Path

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    print("Fehler: Pillow ist nicht installiert. Bitte 'pip install Pillow' ausführen.")
    sys.exit(1)

try:
    from fontTools.ttLib import TTFont
except ImportError:
    print("Hinweis: fonttools nicht installiert ('pip install fonttools'). "
          "Schriftnamen werden aus dem Dateinamen gelesen.")
    TTFont = None


# ── Farbpaletten ──────────────────────────────────────────────────────────────
# upper_bg   — Hintergrund des oberen Bereichs
# lower_bg   — Hintergrund des unteren Bereichs
# accent     — Akzentfarbe für Heroword
# text       — Haupttextfarbe (Aa Ee Rr)
# name_color — Farbe des Fontnamens (abgedunkelt/gedimmt)
# ghost      — Farbe des großen Hintergrundbuchstabens
# lower_text — Textfarbe im unteren Bereich

THEMES = {
    "dark": {
        "upper_bg":   "#1e2035",
        "lower_bg":   "#12141f",
        "accent":     "#b4d273",
        "text":       "#eaeaea",
        "name_color": "#55577a",
        "ghost":      "#252848",
        "lower_text": "#dde0f0",
    },
    "white": {
        "upper_bg":   "#e8e4dc",
        "lower_bg":   "#c8c0a8",
        "accent":     "#7a5c10",
        "text":       "#1a1208",
        "name_color": "#9a9080",
        "ghost":      "#f5f2ec",
        "lower_text": "#faf8f4",
    },
    "cream": {
        "upper_bg":   "#c5baa0",
        "lower_bg":   "#b89354",
        "accent":     "#c8a020",
        "text":       "#1a1208",
        "name_color": "#8a8070",
        "ghost":      "#ddd5c0",
        "lower_text": "#ffffff",
    },
}


def generate_random_theme(mode: str | None = None) -> dict:
    """Leitet harmonische Farben aus einem zufälligen Grundton ab.

    mode: 'dark' | 'light' | 'mid' | None (zufällig aus allen dreien).
    Akzentfarbe nutzt einen triadischen oder split-komplementären Versatz.
    """
    h = random.random()
    h_accent = (h + random.choice([0.33, 0.38, 0.42, 0.58, 0.62, 0.67])) % 1.0
    if mode not in ("dark", "light", "mid"):
        mode = random.choice(["dark", "light", "mid"])

    def hls(hue: float, lightness: float, saturation: float) -> str:
        r, g, b = colorsys.hls_to_rgb(hue % 1.0, lightness, saturation)
        return f"#{int(r * 255):02x}{int(g * 255):02x}{int(b * 255):02x}"

    if mode == "dark":
        return {
            "upper_bg":   hls(h,        0.11, 0.28),
            "lower_bg":   hls(h,        0.07, 0.22),
            "accent":     hls(h_accent, 0.65, 0.80),
            "text":       hls(h,        0.91, 0.12),
            "name_color": hls(h,        0.36, 0.28),
            "ghost":      hls(h,        0.16, 0.24),
            "lower_text": hls(h,        0.88, 0.15),
        }
    elif mode == "light":
        return {
            "upper_bg":   hls(h,        0.91, 0.20),
            "lower_bg":   hls(h,        0.80, 0.28),
            "accent":     hls(h_accent, 0.32, 0.72),
            "text":       hls(h,        0.09, 0.28),
            "name_color": hls(h,        0.60, 0.20),
            "ghost":      hls(h,        0.96, 0.16),
            "lower_text": hls(h,        0.07, 0.22),
        }
    else:  # mid — gesättigte Mitteltöne, heller Text unten / dunkler Text oben
        return {
            "upper_bg":   hls(h,        0.68, 0.42),
            "lower_bg":   hls(h,        0.54, 0.52),
            "accent":     hls(h_accent, 0.20, 0.70),
            "text":       hls(h,        0.06, 0.30),
            "name_color": hls(h,        0.45, 0.32),
            "ghost":      hls(h,        0.80, 0.35),
            "lower_text": hls(h,        0.96, 0.12),
        }


# ── Hilfsfunktionen ───────────────────────────────────────────────────────────

def hex_to_rgb(hex_color: str) -> tuple:
    h = hex_color.lstrip("#")
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))


# Erkennt Subfamily-Keywords am Ende eines Dateinamens (nach - oder _).
# Gruppe 1: optionales Gewicht; Gruppe 2: optional italic/oblique; Gruppe 3: standalone italic/oblique
_SUBFAMILY_RE = re.compile(
    r"^(?:"
    r"(thin|extralight|ultralight|light|regular|book|normal|medium|"
    r"semibold|demibold|bold|extrabold|ultrabold|black|heavy|variable|vf)"
    r"(italic|oblique)?"
    r"|(\[?ital\]?|italic|oblique)"
    r")$",
    re.IGNORECASE,
)


def _strip_axes(s: str) -> str:
    """Entfernt Achsen-Klammern wie [wght,wdth] oder (opsz) aus Dateinamen."""
    return re.sub(r"[\[\(][^\]\)]*[\]\)]", "", s).rstrip("-_ ")


def _parse_name_from_filename(stem: str) -> tuple[str, str]:
    """Parst Familienname und Subfamily aus Dateinamenskonventionen als Fallback."""
    # Achsen-Klammern aus dem Stem entfernen bevor geparst wird
    clean = _strip_axes(stem)
    for sep in ("-", "_"):
        if sep in clean:
            idx = clean.rfind(sep)
            suffix = clean[idx + 1:]
            if _SUBFAMILY_RE.match(suffix):
                return clean[:idx], suffix
    # Kein erkanntes Suffix → bereinigten Stem als Familienname zurückgeben
    return clean, ""


def get_font_name(font_path: str) -> tuple[str, str]:
    """Liest Familienname und Unterfamilie aus den Metadaten der Fontdatei."""
    if TTFont is None:
        return _parse_name_from_filename(Path(font_path).stem)
    try:
        tt = TTFont(font_path)
        name_table = tt["name"]
        def get_name(name_id):
            for record in name_table.names:
                if record.nameID == name_id:
                    try:
                        return record.toUnicode()
                    except Exception:
                        return record.string.decode("latin-1", errors="replace")
            return ""
        family  = get_name(1) or Path(font_path).stem
        sub     = get_name(2) or ""
        pf      = get_name(16)
        ps      = get_name(17)
        if pf:
            family = pf
        if ps:
            sub = ps
        # Variable fonts report the default instance as subfamily (e.g. "Light").
        # Normalise: keep only the italic/oblique signal, drop the weight part.
        if "fvar" in tt:
            s_lower = sub.lower()
            sub = "Italic" if ("italic" in s_lower or "oblique" in s_lower) else ""
        return family.strip(), sub.strip()
    except Exception:
        return Path(font_path).stem, ""


def classify_subfamily(subfamily: str) -> str:
    """Gibt 'regular', 'italic' oder 'other' zurück."""
    # Normalisieren: Leerzeichen, Bindestriche, Unterstriche und Großschreibung entfernen
    s = subfamily.strip().lower().replace(" ", "").replace("-", "").replace("_", "")
    if s in ("", "regular", "roman", "book", "normal", "upright", "variable", "vf"):
        return "regular"
    if s in ("italic", "regularitalic", "oblique", "regularoblique",
             "variableitalic", "vfitalic"):
        return "italic"
    return "other"


def group_fonts_by_family(font_paths: list[str]) -> dict:
    """
    Gruppiert Fontdateien nach Familienname.
    Gibt { family: { "regular": path|None, "italic": path|None } } zurück.
    Nur Regular und Regular-Italic werden berücksichtigt.
    """
    groups: dict[str, dict] = {}
    for path in font_paths:
        family, subfamily = get_font_name(path)
        kind = classify_subfamily(subfamily)
        if kind == "other":
            continue
        if family not in groups:
            groups[family] = {"regular": None, "italic": None}
        if groups[family][kind] is None:
            groups[family][kind] = path
    return groups


def load_wordlist(wordlist_path: str) -> list[str]:
    """Liest Wörter aus einer Textdatei (ein Wort pro Zeile)."""
    try:
        with open(wordlist_path, encoding="utf-8") as f:
            words = [line.strip() for line in f if line.strip()]
        return words if words else ["Hamburgefonstiv"]
    except FileNotFoundError:
        print(f"  Hinweis: Wortliste '{wordlist_path}' nicht gefunden — Fallback wird verwendet.")
        return ["Hamburgefonstiv"]


def load_pil_font(font_path: str, size: int) -> ImageFont.FreeTypeFont:
    # PIL/FreeType kann WOFF und WOFF2 nicht direkt lesen.
    # fontTools konvertiert die Datei im Speicher zu reinem TTF/OTF.
    if font_path.lower().endswith((".woff2", ".woff")):
        if TTFont is None:
            raise RuntimeError(f"fonttools wird für WOFF2 benötigt: {font_path}")
        tt = TTFont(font_path)
        buf = io.BytesIO()
        tt.flavor = None  # WOFF/WOFF2-Wrapper entfernen → reines TTF/CFF
        tt.save(buf)
        buf.seek(0)
        source = buf
    else:
        source = font_path

    font = ImageFont.truetype(source, size)

    # Bei Variable Fonts Standardgewicht auf Regular (400) setzen
    try:
        font.set_variation_by_name("Regular")
    except Exception:
        try:
            font.set_variation_by_axes([400])
        except Exception:
            pass

    return font


def measure(draw: ImageDraw.Draw, text: str, font) -> tuple[int, int]:
    bbox = draw.textbbox((0, 0), text, font=font)
    return bbox[2] - bbox[0], bbox[3] - bbox[1]


# ── Specimen-Zeichnung ────────────────────────────────────────────────────────

def draw_specimen(regular_path: str, output_path: str,
                  italic_path: str | None = None,
                  heroword: str = "Hamburgefonstiv",
                  canvas_width: int = 1000,
                  theme_name: str = "dark") -> None:

    if theme_name.startswith("random"):
        mode_hint = theme_name.removeprefix("random").lstrip("-") or None
        C = generate_random_theme(mode_hint)
    else:
        C = THEMES[theme_name]
    upper_bg   = hex_to_rgb(C["upper_bg"])
    lower_bg   = hex_to_rgb(C["lower_bg"])
    acc_color  = hex_to_rgb(C["accent"])
    txt_color  = hex_to_rgb(C["text"])
    name_color = hex_to_rgb(C["name_color"])
    gst_color  = hex_to_rgb(C["ghost"])
    lower_txt  = hex_to_rgb(C["lower_text"])

    family, _ = get_font_name(regular_path)

    PAD = int(canvas_width * 0.10)

    # ── Mess-Hilfsobjekt (vor Font-Loading — wird für dynamische Namensgröße benötigt)
    tmp_img  = Image.new("RGB", (canvas_width, 200))
    tmp_draw = ImageDraw.Draw(tmp_img)

    def mw(text, font):
        return measure(tmp_draw, text, font)[0]

    def mh(text, font):
        return measure(tmp_draw, text, font)[1]

    # ── Fontname: Größe dynamisch so wählen, dass Name die volle Breite ausfüllt
    _name_target = canvas_width - 2 * PAD
    _ref_sz      = int(canvas_width * 0.14)
    try:
        _ref_font = load_pil_font(regular_path, _ref_sz)
        _ref_w    = mw(family, _ref_font)
        name_sz   = int(_ref_sz * _name_target / max(_ref_w, 1))
        name_sz   = max(min(name_sz, int(canvas_width * 0.42)), int(canvas_width * 0.05))
    except Exception:
        name_sz = _ref_sz

    # ── Schriftgrößen ──────────────────────────────────────────────────────────
    sz = {
        "demo":   int(canvas_width * 0.115),   # "Aa Ee Rr"
        "hero":   int(canvas_width * 0.090),   # Heroword
        "ghost":  int(canvas_width * 0.520),   # Ghost-Buchstabe Hintergrund
        "alpha":  int(canvas_width * 0.075),   # Alphabetreihen (war 0.057)
        "digits": int(canvas_width * 0.068),   # Ziffernreihe (war 0.052)
    }

    def F(key, path=None):
        try:
            return load_pil_font(path or regular_path, sz[key])
        except Exception:
            return ImageFont.load_default()

    try:
        font_name = load_pil_font(regular_path, name_sz)
    except Exception:
        font_name = ImageFont.load_default()
    font_demo_r   = F("demo")
    font_demo_i   = F("demo", italic_path) if italic_path else None
    font_hero     = F("hero", italic_path) if italic_path else F("hero")

    # Alphabet- und Ziffernstrings (mit Zwischenräumen)
    alpha1 = " ".join("abcdefghijklm")
    alpha2 = " ".join("nopqrstuvwxyz")
    digits = " ".join("1234567890")

    # Alpha: Größe dynamisch begrenzen, damit die längste Zeile nicht überläuft
    _alpha_max = int(canvas_width * 0.075)
    _alpha_tgt = canvas_width - 2 * PAD
    try:
        font_alpha = load_pil_font(regular_path, _alpha_max)
        _alpha_w   = mw(alpha1, font_alpha)
        if _alpha_w > _alpha_tgt:
            _alpha_sz  = max(20, int(_alpha_max * _alpha_tgt / _alpha_w))
            font_alpha = load_pil_font(regular_path, _alpha_sz)
    except Exception:
        font_alpha = ImageFont.load_default()

    font_digits_r = F("digits")

    # ── Höhe berechnen ─────────────────────────────────────────────────────────
    LINE_S = int(canvas_width * 0.022)   # enger Zeilenabstand (zwischen Demo-Zeilen)
    LINE_M = int(canvas_width * 0.038)   # mittlerer Abstand
    LINE_L = int(canvas_width * 0.052)   # großer Abstand (nach Fontname)

    name_h    = mh(family, font_name)
    name_top  = tmp_draw.textbbox((0, 0), family, font=font_name)[1]
    demo_r_h  = mh("Aa Ee Rr", font_demo_r)
    demo_i_h  = mh("Aa Ee Rr", font_demo_i) if font_demo_i else 0
    hero_h    = mh(heroword, font_hero)
    alpha_h   = mh(alpha1, font_alpha)
    digits_h  = mh(digits, font_digits_r)

    upper_h = (PAD
               + name_h + LINE_L
               + demo_r_h + LINE_S
               + (demo_i_h + LINE_M if font_demo_i else 0)
               + hero_h
               + PAD)

    # Ghost-Buchstabe: Größe auf den verfügbaren Bereich begrenzen.
    # Erlaubter Bereich: rechts vom Text, zwischen "Aa Ee Rr"-Oberkante und unterem Rand.
    ghost_top_bound = PAD + name_h + LINE_L
    ghost_bot_bound = upper_h - PAD
    ghost_avail_h   = ghost_bot_bound - ghost_top_bound
    ghost_sz = sz["ghost"]
    try:
        _ghost_test = load_pil_font(regular_path, ghost_sz)
        _gb = tmp_draw.textbbox((0, 0), "a", font=_ghost_test)
        _ghost_h = _gb[3] - _gb[1]
        if _ghost_h > ghost_avail_h:
            ghost_sz = max(50, int(ghost_sz * ghost_avail_h / _ghost_h))
    except Exception:
        pass
    try:
        font_ghost = load_pil_font(regular_path, ghost_sz)
    except Exception:
        font_ghost = ImageFont.load_default()

    lower_h = (PAD
               + alpha_h + int(LINE_S * 0.8)
               + alpha_h + LINE_M
               + digits_h
               + PAD)

    canvas_height = upper_h + lower_h

    # ── Canvas + Hintergründe ──────────────────────────────────────────────────
    img  = Image.new("RGB", (canvas_width, canvas_height), upper_bg)
    draw = ImageDraw.Draw(img)

    # ── Ghost-Buchstabe (Hintergrund, rechts) ────────────────────────────────
    # Ghost vor dem unteren Rechteck zeichnen, damit lower_bg als Clip-Maske wirkt.
    demo_end = PAD + max(
        mw("Aa Ee Rr", font_demo_r),
        mw("Aa Ee Rr", font_demo_i) if font_demo_i else 0,
    )
    ghost_bbox = draw.textbbox((0, 0), "a", font=font_ghost)
    ghost_x = demo_end + int(canvas_width * 0.02) - ghost_bbox[0]
    ghost_y = ghost_top_bound - ghost_bbox[1]
    draw.text((ghost_x, ghost_y), "a", font=font_ghost, fill=acc_color)

    # Unterer Hintergrund nach Ghost zeichnen → schneidet Überlauf sauber ab
    draw.rectangle([(0, upper_h), (canvas_width, canvas_height)], fill=lower_bg)

    # ── Oberer Bereich — Text ─────────────────────────────────────────────────
    y = PAD

    # Fontname — visuell bündig zum oberen Rand, unabhängig vom internen Glyph-Offset
    draw.text((PAD, y - name_top), family, font=font_name, fill=name_color)
    y += name_h + LINE_L

    # "Aa Ee Rr" Regular
    draw.text((PAD, y), "Aa Ee Rr", font=font_demo_r, fill=txt_color)
    y += demo_r_h + LINE_S

    # "Aa Ee Rr" Italic (nur wenn Italic-Schnitt vorhanden)
    if font_demo_i:
        draw.text((PAD, y), "Aa Ee Rr", font=font_demo_i, fill=txt_color)
        y += demo_i_h + LINE_M

    # Heroword in Akzentfarbe (Italic wenn vorhanden)
    draw.text((PAD, y), heroword, font=font_hero, fill=acc_color)

    # ── Unterer Bereich — Alphabet + Ziffern ──────────────────────────────────
    y = upper_h + PAD

    draw.text((PAD, y), alpha1, font=font_alpha, fill=lower_txt)
    y += alpha_h + int(LINE_S * 0.8)

    draw.text((PAD, y), alpha2, font=font_alpha, fill=lower_txt)
    y += alpha_h + LINE_M

    # Ziffern: rechtsbündig, nur Regular — Italic sieht bei Ziffern kaum anders aus
    # und wurde bereits durch die "Aa Ee Rr"-Zeile oben gezeigt.
    digits_r_w = mw(digits, font_digits_r)
    x_r = canvas_width - PAD - digits_r_w
    draw.text((x_r, y), digits, font=font_digits_r, fill=lower_txt)

    # ── Speichern ──────────────────────────────────────────────────────────────
    img.save(output_path, "PNG", optimize=True)
    italic_info = " + Italic" if italic_path else ""
    print(f"  ✓  {Path(output_path).name}  [{canvas_width}×{canvas_height}px]  ({family}{italic_info})")


# ── Ordner-Scan & Batch-Verarbeitung ─────────────────────────────────────────

FONT_EXTENSIONS = {".ttf", ".otf", ".woff", ".woff2"}


def find_fonts(folder: str) -> list[str]:
    found = []
    for root, _, files in os.walk(folder):
        for f in sorted(files):
            if Path(f).suffix.lower() in FONT_EXTENSIONS:
                found.append(os.path.join(root, f))
    return found


def slugify(name: str) -> str:
    return "".join(c if c.isalnum() or c in "-_" else "_" for c in name)


def process_folder(input_folder: str, output_folder: str,
                   width: int = 1000, theme: str = "dark",
                   overwrite: bool = False,
                   wordlist_path: str | None = None) -> None:

    os.makedirs(output_folder, exist_ok=True)
    all_fonts = find_fonts(input_folder)

    if not all_fonts:
        print(f"Keine Schriftdateien in '{input_folder}' gefunden.")
        print(f"Unterstützte Formate: {', '.join(sorted(FONT_EXTENSIONS))}")
        return

    families = group_fonts_by_family(all_fonts)
    families_with_regular = {k: v for k, v in families.items() if v["regular"]}
    skipped_no_regular = len(families) - len(families_with_regular)

    default_wordlist = Path(__file__).parent / "wordlist.txt"
    words = load_wordlist(str(wordlist_path) if wordlist_path else str(default_wordlist))

    print(f"\nFont Specimen Generator")
    print(f"{'─' * 50}")
    print(f"Eingabe:  {input_folder}")
    print(f"Ausgabe:  {output_folder}")
    print(f"Breite:   {width}px   Theme: {theme}")
    print(f"Dateien gefunden: {len(all_fonts)}  →  Familien: {len(families_with_regular)}"
          + (f"  ({skipped_no_regular} ohne Regular übersprungen)" if skipped_no_regular else ""))
    print(f"{'─' * 50}\n")

    ok = skip = err = 0

    for family, cuts in families_with_regular.items():
        regular_path = cuts["regular"]
        italic_path  = cuts["italic"]
        safe_name    = slugify(family)
        out_name     = f"{safe_name}.png"
        out_path     = os.path.join(output_folder, out_name)

        if not overwrite and os.path.exists(out_path):
            print(f"  –  {out_name}  (übersprungen, bereits vorhanden)")
            skip += 1
            continue

        heroword = random.choice(words)

        try:
            draw_specimen(
                regular_path=regular_path,
                output_path=out_path,
                italic_path=italic_path,
                heroword=heroword,
                canvas_width=width,
                theme_name=theme,
            )
            ok += 1
        except Exception as e:
            print(f"  ✗  {family}  →  Fehler: {e}")
            err += 1

    print(f"\n{'─' * 50}")
    print(f"Fertig!  ✓ {ok} erstellt   – {skip} übersprungen   ✗ {err} Fehler")
    print(f"Vorschauen in: {os.path.abspath(output_folder)}\n")


# ── Einstiegspunkt ────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generiert Font-Specimen-Vorschaubilder für alle Schriftfamilien in einem Ordner.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Beispiele:
  python font_specimen_generator.py --input ./fonts --output ./previews
  python font_specimen_generator.py --input ./fonts --output ./previews --theme white
  python font_specimen_generator.py --input ./fonts --output ./previews --width 1400 --theme cream
  python font_specimen_generator.py --input ./fonts --output ./previews --overwrite
  python font_specimen_generator.py --input ./fonts --output ./previews --wordlist ./meine_woerter.txt
        """
    )
    parser.add_argument("--input",    "-i", required=True,
                        help="Ordner mit Schriftdateien (wird rekursiv durchsucht)")
    parser.add_argument("--output",   "-o", required=True,
                        help="Ausgabeordner für die PNG-Vorschauen")
    parser.add_argument("--width",    "-w", type=int, default=1000,
                        help="Breite der Vorschaubilder in Pixel (Standard: 1000)")
    parser.add_argument("--theme",    "-t", default="dark",
                        choices=list(THEMES.keys()) + ["random", "random-dark", "random-light"],
                        help="Farbschema: dark | white | cream | random | random-dark | random-light (Standard: dark)")
    parser.add_argument("--wordlist", default=None,
                        help="Pfad zur Wortliste (Standard: wordlist.txt neben dem Script)")
    parser.add_argument("--overwrite", action="store_true",
                        help="Bereits vorhandene Vorschauen überschreiben")

    args = parser.parse_args()

    if args.width < 400:
        print("Fehler: Mindestbreite ist 400px.")
        sys.exit(1)

    process_folder(
        input_folder  = args.input,
        output_folder = args.output,
        width         = args.width,
        theme         = args.theme,
        overwrite     = args.overwrite,
        wordlist_path = args.wordlist,
    )


if __name__ == "__main__":
    main()
