"""
generate_font_specimens.py
generated by Claude Ai

Font Specimen Generator
=======================
Durchsucht einen Ordner nach Schriftdateien (.ttf, .otf, .woff, .woff2)
und erstellt für jede Schrift eine Vorschau im Stil der Wikipedia Font Specimens.

Benötigte Bibliotheken:
    pip install Pillow fonttools

Verwendung:
    python font_specimen_generator.py --input ./fonts --output ./previews
    python font_specimen_generator.py --input ./fonts --output ./previews --width 1200 --bg white
"""

import argparse
import os
import sys
from pathlib import Path

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    print("Fehler: Pillow ist nicht installiert. Bitte 'pip install Pillow' ausführen.")
    sys.exit(1)

try:
    from fontTools.ttLib import TTFont
except ImportError:
    print("Hinweis: fonttools nicht installiert ('pip install fonttools'). "
          "Schriftnamen werden aus dem Dateinamen gelesen.")
    TTFont = None


# ── Farbpaletten ──────────────────────────────────────────────────────────────

THEMES = {
    "dark": {
        "bg":          "#1a1a2e",
        "header_bg":   "#16213e",
        "accent":      "#b4d273",
        "text":        "#eaeaea",
        "text_dim":    "#a0a0b0",
        "divider":     "#2a2a4a",
        "large_ghost": "#252540",
        "label_bg":    "#0f3460",
        "label_text":  "#e0e0ff",
    },
    "white": {
        "bg":          "#ffffff",
        "header_bg":   "#f5f5f5",
        "accent":      "#0f3460",
        "text":        "#111111",
        "text_dim":    "#555555",
        "divider":     "#dddddd",
        "large_ghost": "#f0f0f0",
        "label_bg":    "#eeeeee",
        "label_text":  "#333333",
    },
    "cream": {
        "bg":          "#fdf6e3",
        "header_bg":   "#f5e6c8",
        "accent":      "#8b4513",
        "text":        "#1a1a1a",
        "text_dim":    "#5a4a3a",
        "divider":     "#d4c5a9",
        "large_ghost": "#776d5e",
        "label_bg":    "#d4b896",
        "label_text":  "#3a2a1a",
    },
}


# ── Hilfsfunktionen ───────────────────────────────────────────────────────────

def hex_to_rgb(hex_color: str) -> tuple:
    h = hex_color.lstrip("#")
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))


def get_font_name(font_path: str) -> tuple[str, str]:
    """Liest Familienname und Unterfamilie aus den Metadaten der Fontdatei."""
    if TTFont is None:
        stem = Path(font_path).stem
        return stem, ""
    try:
        tt = TTFont(font_path)
        name_table = tt["name"]
        def get_name(name_id):
            for record in name_table.names:
                if record.nameID == name_id:
                    try:
                        return record.toUnicode()
                    except Exception:
                        return record.string.decode("latin-1", errors="replace")
            return ""
        family   = get_name(1) or Path(font_path).stem
        sub      = get_name(2) or ""
        preferred_family = get_name(16)
        preferred_sub    = get_name(17)
        if preferred_family:
            family = preferred_family
        if preferred_sub:
            sub = preferred_sub
        return family.strip(), sub.strip()
    except Exception:
        return Path(font_path).stem, ""


def load_pil_font(font_path: str, size: int) -> ImageFont.FreeTypeFont:
    return ImageFont.truetype(font_path, size)


def text_size(draw: ImageDraw.Draw, text: str, font) -> tuple[int, int]:
    bbox = draw.textbbox((0, 0), text, font=font)
    return bbox[2] - bbox[0], bbox[3] - bbox[1]


# ── Specimen-Zeichnung ────────────────────────────────────────────────────────

def draw_specimen(font_path: str, output_path: str,
                  canvas_width: int = 1000,
                  theme_name: str = "dark") -> None:

    C = THEMES[theme_name]
    bg_color   = hex_to_rgb(C["bg"])
    hdr_color  = hex_to_rgb(C["header_bg"])
    acc_color  = hex_to_rgb(C["accent"])
    txt_color  = hex_to_rgb(C["text"])
    dim_color  = hex_to_rgb(C["text_dim"])
    div_color  = hex_to_rgb(C["divider"])
    gst_color  = hex_to_rgb(C["large_ghost"])
    lbl_bg     = hex_to_rgb(C["label_bg"])
    lbl_txt    = hex_to_rgb(C["label_text"])

    family, subfamily = get_font_name(font_path)
    full_name = f"{family}  {subfamily}".strip()

    PAD   = int(canvas_width * 0.095)
    inner = canvas_width - 2 * PAD

    # ── Schriftgrößen ──────────────────────────────────────────────────────────
    sz = {
        "display":  int(canvas_width * 0.2130),
        "heading":  int(canvas_width * 0.068),
        "chars":    int(canvas_width * 0.090),
        "alphabet": int(canvas_width * 0.068),
        "body_lg":  int(canvas_width * 0.030),
        "body_md":  int(canvas_width * 0.024),
        "body_sm":  int(canvas_width * 0.018),
        "label":    int(canvas_width * 0.014),
        "meta":     int(canvas_width * 0.016),
    }

    def F(key):
        try:
            return load_pil_font(font_path, sz[key])
        except Exception:
            return ImageFont.load_default()

    fonts = {k: F(k) for k in sz}

    # ── Hilfsobjekt zum Messen (temporär) ─────────────────────────────────────
    tmp_img  = Image.new("RGB", (canvas_width, 100))
    tmp_draw = ImageDraw.Draw(tmp_img)

    def tw(text, fkey):
        return text_size(tmp_draw, text, fonts[fkey])[0]

    def th(text, fkey):
        return text_size(tmp_draw, text, fonts[fkey])[1]

    # ── Inhaltsblöcke vordefinieren ────────────────────────────────────────────
    UPPER  = "ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜẞ"
    LOWER  = "abcdefghijklmn" + "\n" + "opqrstuvwxyzäöüß"
    DIGITS = "0123456789 @$%&?"
    PUNCT  = "@ „ “ ! \" # $ % & ' ( ) * + , - . / : ; < = > ? @ [ \\ ] ^ _ ` { | } ~"

    SAMPLES = [
        # ("Hamburgefonts", "heading"),
        (LOWER, "heading"),
        (DIGITS, "heading"),
        ("The stiffi fly likes sparkly stones", "heading"),
        ("Zwölf Boxkämpfer jagen Viktor quer über den großen Sylter Deich. Jovencillo emponzoñado de whisky: ¡qué figurota exhibe! Voyez le brick géant que j'examine près du wharf The quick brown fox jumps over the lazy dog. Pack my box with five dozen liquor jugs.", "body_lg"),
        # ("Zwölf Boxkämpfer jagen Viktor quer über den großen\n Sylter Deich. Jovencillo emponzoñado de whisky: ¡qué figurota exhibe! \n Voyez le brick géant que j'examine près du wharf The quick brown fox jumps over the lazy dog. Pack my box with five dozen liquor jugs.", "body_md"),
        # ("Zwölf Boxkämpfer jagen Viktor quer über den großen\n Sylter Deich. Jovencillo emponzoñado de whisky: ¡qué figurota exhibe! \n Voyez le brick géant que j'examine près du wharf The quick brown fox jumps over the lazy dog. Pack my box with five dozen liquor jugs.", "body_sm"),
    ]

    SIZE_WATERFALL = [
        (int(canvas_width * 0.060), "Hamburgefonstiv"),
        (int(canvas_width * 0.048), "Hamburgefonstiv"),
        (int(canvas_width * 0.038), "Hamburgefonstiv"),
        (int(canvas_width * 0.028), "Hamburgefonstiv"),
        (int(canvas_width * 0.022), "The quick brown fox jumps over the lazy dog."),
        (int(canvas_width * 0.017), "The quick brown fox jumps over the lazy dog."),
        (int(canvas_width * 0.013), "The quick brown fox jumps over the lazy dog."),
    ]

    # ── Höhe berechnen ─────────────────────────────────────────────────────────
    LINE_GAP = int(canvas_width * 0.0218)
    SECTION  = int(canvas_width * 0.030)

    header_h = int(canvas_width * 0.214)

    def calc_height():
        y = header_h + PAD
        # Ghost-Display-Buchstaben + Heading
        y += int(canvas_width * 0.16) + LINE_GAP
        # Alphabet-Blöcke (4 Zeilen + Labels)
        # for _ in (UPPER, LOWER, DIGITS, PUNCT):
        for _ in (LOWER, DIGITS):
            y += int(canvas_width * 0.020) + th("A", "alphabet") + LINE_GAP
        y += SECTION
        y += 1  # divider
        y += SECTION
        # Textproben
        for _, fkey in SAMPLES:
            y += th("A", fkey) + LINE_GAP
        y += SECTION
        y += 1
        y += SECTION
        # Größenwasserfall
        for size, _ in SIZE_WATERFALL:
            try:
                f = load_pil_font(font_path, size)
            except Exception:
                f = ImageFont.load_default()
            y += text_size(tmp_draw, "A", f)[1] + LINE_GAP
        y += PAD * 2
        return y

    canvas_height = calc_height()

    # ── Canvas erstellen ───────────────────────────────────────────────────────
    img  = Image.new("RGB", (canvas_width, canvas_height), bg_color)
    draw = ImageDraw.Draw(img)

    # ── Header ────────────────────────────────────────────────────────────────
    draw.rectangle([(0, 0), (canvas_width, header_h)], fill=hdr_color)
    # Akzentbalken links
    bar_w = int(canvas_width * 0.008)
    draw.rectangle([(0, 0), (bar_w, header_h)], fill=acc_color)
    # Unterer Akzentbalken
    # bar_top_y = header_h
    # draw.rectangle([(0, 0), (canvas_width, bar_top_y)],
    #                fill=gst_color)
    # bar_w = 0

    # Fontname
    fn_font = fonts["heading"]
    fn_w    = tw(family, "heading")
    draw.text((PAD + bar_w + int(PAD * 0.030),
               (header_h - sz["heading"]) // 2 - int(canvas_width * 0.005)),
              family, font=fn_font, fill=acc_color)

    # if subfamily:
    #     sub_y = (header_h - sz["heading"]) // 2 + sz["heading"] - int(canvas_width * 0.005)
    #     draw.text((PAD + bar_w + int(PAD * 0.030), sub_y),
    #               subfamily, font=fonts["meta"], fill=dim_color)

    # Dateipfad rechts
    path_str = Path(font_path).name
    path_w   = tw(path_str, "label")
    draw.text((canvas_width - PAD - path_w,
               header_h - int(canvas_width * 0.030)),
              path_str, font=fonts["label"], fill=dim_color)

    # ── Zeichenbereich ─────────────────────────────────────────────────────────
    y = header_h + PAD

    # Großer Ghost-Buchstabe im Hintergrund + darunter Headline-Demo
    ghost_font = fonts["display"]
    # ghost_txt  = family[:2].upper() if len(family) >= 2 else family[0].upper()
    # ghost_txt  = family[:2] if len(family) >= 2 else family[0]
    ghost_txt  = "Aá"
    ghost_w, ghost_h = text_size(draw, ghost_txt, ghost_font)
    ghost_x = canvas_width - PAD - ghost_w - int(canvas_width * 0.02)
    draw.text((ghost_x, y - int(canvas_width * 0.012)),
              ghost_txt, font=ghost_font, fill=gst_color)

    # Heading-Demo
    # demo_txt   = "Aa Ee Rr 1ilL" + '\n' + family
    demo_txt   = "Aa Ee Rr" + '\n' "Gg Jj Mm" + '\n' "Rr Ww Ii"
    demo_font  = fonts["chars"]
    demo_h     = th(demo_txt, "chars")
    draw.text((PAD, y), demo_txt, font=demo_font, fill=txt_color)
    y += demo_h + LINE_GAP * 1.5

    # ── Alphabet-Sektionen ─────────────────────────────────────────────────────
    def draw_char_row(label_text, char_string, y_pos):
        # Label
        lbl_font = fonts["label"]
        lbl_h    = th(label_text, "label")
        lbl_w    = tw(label_text, "label")
        lbl_pad  = int(canvas_width * 0.010)
        draw.rectangle([(PAD, y_pos),
                        (PAD + lbl_w + lbl_pad * 2, y_pos + lbl_h + lbl_pad)],
                       fill=lbl_bg)
        draw.text((PAD + lbl_pad, y_pos + lbl_pad // 2),
                  label_text, font=lbl_font, fill=lbl_txt)
        y_pos += lbl_h + lbl_pad + int(canvas_width * 0.008)

        # Zeichen
        af = fonts["alphabet"]
        draw.text((PAD, y_pos), char_string, font=af, fill=txt_color)
        y_pos += th(char_string, "alphabet") + LINE_GAP
        return y_pos

    # y = draw_char_row("GROSSBUCHSTABEN", UPPER, y)
    # y = draw_char_row("kleinbuchstaben", LOWER, y)
    # y = draw_char_row("Ziffern",         DIGITS, y)
    # y = draw_char_row("Satzzeichen",     PUNCT,  y)

    y += SECTION

    # Trennlinie
    draw.rectangle([(PAD, y), (canvas_width - PAD, y + 1)], fill=div_color)
    y += SECTION

    # ── Textproben ─────────────────────────────────────────────────────────────
    section_label = "TEXTPROBEN"
    sl_font = fonts["label"]
    draw.text((PAD, y), section_label, font=sl_font, fill=dim_color)
    y += th(section_label, "label") + int(LINE_GAP * 0.8)

    for sample_text, fkey in SAMPLES:
        sf = fonts[fkey]
        # Langer Text: umbrechen wenn nötig
        max_w = inner
        words = sample_text.split()
        lines_out = []
        cur = ""
        for w in words:
            test = (cur + " " + w).strip()
            if tw(test, fkey) <= max_w:
                cur = test
            else:
                if cur:
                    lines_out.append(cur)
                cur = w
        if cur:
            lines_out.append(cur)

        for line in lines_out:
            draw.text((PAD, y), line, font=sf, fill=txt_color, features=["liga", "ss01"])
            y += th(line, fkey) + int(LINE_GAP * 0.6)
        y += LINE_GAP

    y += SECTION

    # Trennlinie
    draw.rectangle([(PAD, y), (canvas_width - PAD, y + 1)], fill=div_color)
    y += SECTION

    # # ── Größenwasserfall ───────────────────────────────────────────────────────
    # section_label2 = "GRÖSSENWASSERFAll"
    # draw.text((PAD, y), section_label2, font=fonts["label"], fill=dim_color)
    # y += th(section_label2, "label") + int(LINE_GAP * 0.8)

    # for size, wf_text in SIZE_WATERFALL:
    #     try:
    #         wf_font = load_pil_font(font_path, size)
    #     except Exception:
    #         wf_font = ImageFont.load_default()
    #     # Größenangabe (rechts)
    #     size_str  = f"{size}px"
    #     size_font = fonts["label"]
    #     size_w    = tw(size_str, "label")
    #     draw.text((canvas_width - PAD - size_w, y + (size - sz["label"]) // 2),
    #               size_str, font=size_font, fill=dim_color)
    #     # Wortprobe
    #     wh = text_size(draw, wf_text, wf_font)[1]
    #     draw.text((PAD, y), wf_text, font=wf_font, fill=txt_color)
    #     y += wh + LINE_GAP

    # # ── Footer ─────────────────────────────────────────────────────────────────
    # y += SECTION
    # footer = f"Font Specimen  ·  {full_name}  ·  {Path(font_path).suffix.upper().lstrip('.')}"
    # draw.text((PAD, y), footer, font=fonts["label"], fill=dim_color)

    # Unterer Akzentbalken
    bar_bottom_y = canvas_height - int(canvas_width * 0.005)
    draw.rectangle([(0, bar_bottom_y), (canvas_width, canvas_height)],
                   fill=acc_color)

    # ── Speichern ──────────────────────────────────────────────────────────────
    img.save(output_path, "PNG", optimize=True)
    print(f"  ✓  {Path(output_path).name}  [{canvas_width}×{canvas_height}px]")


# ── Ordner-Scan & Batch-Verarbeitung ─────────────────────────────────────────

FONT_EXTENSIONS = {".ttf", ".otf", ".woff", ".woff2"}


def find_fonts(folder: str) -> list[str]:
    found = []
    for root, _, files in os.walk(folder):
        for f in sorted(files):
            if Path(f).suffix.lower() in FONT_EXTENSIONS:
                found.append(os.path.join(root, f))
    return found


def slugify(name: str) -> str:
    return "".join(c if c.isalnum() or c in "-_" else "_" for c in name)


def process_folder(input_folder: str, output_folder: str,
                   width: int = 1000, theme: str = "dark",
                   overwrite: bool = False) -> None:

    os.makedirs(output_folder, exist_ok=True)
    fonts = find_fonts(input_folder)

    if not fonts:
        print(f"Keine Schriftdateien in '{input_folder}' gefunden.")
        print(f"Unterstützte Formate: {', '.join(sorted(FONT_EXTENSIONS))}")
        return

    print(f"\nFont Specimen Generator")
    print(f"{'─' * 50}")
    print(f"Eingabe:  {input_folder}")
    print(f"Ausgabe:  {output_folder}")
    print(f"Breite:   {width}px   Theme: {theme}")
    print(f"Schriften gefunden: {len(fonts)}")
    print(f"{'─' * 50}\n")

    ok = skip = err = 0

    for font_path in fonts:
        family, subfamily = get_font_name(font_path)
        safe_name  = slugify(f"{family}_{subfamily}" if subfamily else family)
        out_name   = f"{safe_name}.png"
        out_path   = os.path.join(output_folder, out_name)

        if not overwrite and os.path.exists(out_path):
            print(f"  –  {out_name}  (übersprungen, bereits vorhanden)")
            skip += 1
            continue

        try:
            draw_specimen(font_path, out_path, width, theme)
            ok += 1
        except Exception as e:
            print(f"  ✗  {Path(font_path).name}  →  Fehler: {e}")
            err += 1

    print(f"\n{'─' * 50}")
    print(f"Fertig!  ✓ {ok} erstellt   – {skip} übersprungen   ✗ {err} Fehler")
    print(f"Vorschauen in: {os.path.abspath(output_folder)}\n")


# ── Einstiegspunkt ────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generiert Font-Specimen-Vorschaubilder für alle Schriften in einem Ordner.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Beispiele:
  python font_specimen_generator.py --input ./fonts --output ./previews
  python font_specimen_generator.py --input ./fonts --output ./previews --theme white
  python font_specimen_generator.py --input ./fonts --output ./previews --width 1400 --theme cream
  python font_specimen_generator.py --input ./fonts --output ./previews --overwrite
        """
    )
    parser.add_argument("--input",  "-i", required=True,
                        help="Ordner mit Schriftdateien (wird rekursiv durchsucht)")
    parser.add_argument("--output", "-o", required=True,
                        help="Ausgabeordner für die PNG-Vorschauen")
    parser.add_argument("--width",  "-w", type=int, default=1000,
                        help="Breite der Vorschaubilder in Pixel (Standard: 1000)")
    parser.add_argument("--theme",  "-t", default="dark",
                        choices=list(THEMES.keys()),
                        help="Farbschema: dark | white | cream (Standard: dark)")
    parser.add_argument("--overwrite", action="store_true",
                        help="Bereits vorhandene Vorschauen überschreiben")

    args = parser.parse_args()

    if args.width < 400:
        print("Fehler: Mindestbreite ist 400px.")
        sys.exit(1)

    process_folder(
        input_folder  = args.input,
        output_folder = args.output,
        width         = args.width,
        theme         = args.theme,
        overwrite     = args.overwrite,
    )


if __name__ == "__main__":
    main()
