title: Fira Code
url: https://github.com/tonsky/FiraCode
wikipedia: https://en.wikipedia.org/wiki/Fira_(typeface)

tags: Monospace, Coding

comment: "Meine frühere Monospace-Schrift. Ich lasse sie schweren Herzens hinter mir, aber JetBrains Mono ist einfach angenehmer anzuschauen."

fontauthor: Nikita Prokopov
fontyear: 2014

heroletter: Aá
heroword: Codeword

herostyle:
color: limegreen
border: hash.svg
