title: Fira Code
url: https://github.com/tonsky/FiraCode
wikipedia: https://en.wikipedia.org/wiki/Fira_(typeface)

tags: Monospace, Coding

comment: "My former monotype font. I sadly leave it behind, but JetBrains Mono is just nicer to stare at."

fontauthor: Nikita Prokopov
fontyear: 2014

heroletter: Aá
heroword: Codeword

herostyle:
color: limegreen
border: hash.svg
