title: Dancing Script
url: https://fonts.google.com/specimen/Dancing+Script

tags: Script, Kalligraphisch

fontauthor: Pablo Impallari
fontyear: 2011

heroletter: Dd
heroword: "Dancing"
color: plum

content: |
  Dancing Script von Pablo Impallari ist eine fließende kalligrafische Schrift mit lebhaftem, fröhlichem Charakter. Verbundene Buchstaben und variierende Buchstabengrößen imitieren natürlichen Schreibfluss. Verglichen mit Satisfy ist sie weniger formal und besitzt mehr Bewegung und Energie — ein anderes emotionales Register innerhalb der gleichen Gattung.
