title: Tex Gyre Pagella
url: https://www.gust.org.pl/projects/e-foundry/tex-gyre
wikipedia: https://en.wikipedia.org/wiki/Palatino

tags: Humanist, Serif, Garalde

comment: "TeX Gyre Pagella can be used as a replacement for the renowned Palatino font (designed by Hermann Zapf in the 1940's for the Stempel type foundry)"

fontauthor: Bogusław Jackowski, Janusz M. Nowacki, Piotr Strzelczyk
fontyear: 2006

heroletter: Aa
heroword: Zapfen
herostyle:
color: MediumSlateBlue
