title: Grenze Gotisch
url: https://www.omnibus-type.com/fonts/grenze-gotisch/

tags: Blackletter, Display, Script, Serif

comment: "Identisch mit Grenze, aber mit ein paar dramatischen Details."

fontauthor: Renata Polastri & Omnibus-Type Team
fontyear: 2020

heroletter: Aa
heroword: Gothic
herostyle:

