title: Quicksand
url: https://github.com/ThomasJockin/QuicksandFamily

tags: Sans, Geometric, Rounded, Variable

fontauthor: Andrew Paglinawan
fontyear: 2008

heroletter: Qq
heroword: Quick

content: |
  Quicksand ist eine geometrische Grotesque mit rundenden Ecken und Übergängen, die einen freundlichen und modernen Charakter verleiht. Die variable Schrift ergänzt perfekt andere geometrische Serifenlosen in dieser Sammlung wie Jost* und Metropolis und bietet damit erstmals eine echte gerundete Alternative in dieser Kategorie.

color: mediumturquoise
