title: Blackletter fonts


content: |
  Über viele Jahrhunderte hinweg prägten gebrochene Schriften (auch als Fraktur im Deutschen bekannt) das Schriftbild im deutschsprachigen Raum und wurden bis ins 20. Jahrhundert als Standardschrift für Bücher, Zeitungen und offizielle Dokumente angesehen.

    Besonders geeignet für:
  - Historische und traditionelle Gestaltung
  - Dekorative Überschriften
  - Musik-, Bier- und Brauereimarken