title: Big Shoulders Stencil
url: https://github.com/xotypeco/big_shoulders

tags: Display, Stencil, Condensed, Variable

fontauthor: Patric King (XOType)
fontyear: 2019

heroletter: Ss
heroword: CUTS
herostyle: bold
color: yellowgreen

content: |
  Big Shoulders Stencil von Patric King ist die Stencil-Variante der Big Shoulders, einer schmalen amerikanischen Gotisch. Mit ausgestanzten, offenen Letterformen erweitert sie die Big Shoulders-Familie um kraftvolle Ausschnitt-Typografie für prägnante Headlines. Zwei Achsen: Gewicht von 100 bis 900 und optische Größe von 10 bis 72. Ein modernes Echo der chicagoer Plakatkultur, scharfkantig und unverwechselbar.
