title: Gentium Plus
url: https://software.sil.org/gentium

tags: Serif, Garalde, Old Style

fontauthor: Victor Gaultney (SIL International)
fontyear: 2003

heroletter: Gg
heroword: "Gentium"
color: saddlebrown

content: |
  Gentium Plus von SIL International ist ein scholastisch-humanistischer Old-Style-Serif mit außergewöhnlicher Unicode-Abdeckung, die linguistische und akademische Texte in vielen Sprachen und Schriftsystemen ermöglicht. Als freie Schrift von wissenschaftlicher Qualität ergänzt er Junicode um eine andere historische Referenz und einen anderen gestalterischen Ausgangspunkt.
