title: Bodoni*
url: https://github.com/indestructible-type/Bodoni
wikipedia: "https://de.wikipedia.org/wiki/Bodoni_(Schriftart)"

tags: Serif, Didone, Display

fontauthor: Owen Earl
fontyear: 1549

heroletter: Bd
heroword: Vita nuova
herostyle: bold

border: floral.svg

content: |
  Bodoni* von Owen Earl ist eine zeitgemäße Interpretation der klassischen Didone-Schrift, die Giambattista Bodoni Ende des 18. Jahrhunderts an der Druckerei des Herzogs von Parma entwarf. Der extreme Kontrast zwischen feinen Haarstrichen und kräftigen Grundstrichen macht Bodoni zum Inbegriff eleganter Display-Typografie.
