title: Bodoni*
url: https://github.com/indestructible-type/Bodoni
wikipedia: https://en.wikipedia.org/wiki/Bodoni

tags: Serif, Didone, Display

fontauthor: Owen Earl
fontyear: 1549

heroletter: Bd
heroword: Vita nuova
herostyle: bold
color: olivedrab
border: floral.svg
