title: TeX Gyre Chorus
url: https://www.gust.org.pl/projects/e-foundry/tex-gyre/chorus

tags: Script, Kalligraphisch

fontauthor: Bogusław Jackowski, Janusz M. Nowacki (GUST e-foundry)
fontyear: 2007

heroletter: Cc
heroword: Eleganz
color: orchid
content: |
  TeX Gyre Chorus ist eine freie Alternative zur berühmten ITC Zapf Chancery, entworfen 1979 von Hermann Zapf. Basierend auf der URW Chancery L Medium Italic, bietet diese Schrift die elegante Handschriftlichkeit einer klassischen Kalligraphie. Als einziges Schriftgewicht „Medium Italic" bewahrt Chorus die authentische Kursivität und ist ideal für formale Schriftzüge, Einladungen und elegante typografische Akzente.
