title: STIX Two
url: https://www.stixfonts.org

tags: Serif, Humanist

fontauthor: STI Pub Companies / Tiro Typeworks
fontyear: 2021

heroletter: Ss
heroword: "∑ STIX"
color: darkslateblue

content: |
  STIX Two wurde von einem Konsortium wissenschaftlicher Verlage (STI Pub) entwickelt und von Tiro Typeworks umgesetzt, um einen einheitlichen Standard für mathematisch-wissenschaftlichen Satz im Web zu schaffen. Mit vollständiger Math-Unterstützung nach OpenType MATH-Spezifikation ist sie die einzige Schrift in der Sammlung, die technische Typografie als primären Anwendungsfall adressiert.
