title: League Spartan
url: https://theleagueofmoveabletype.com/league-spartan

tags: Sans, Geometric, Grotesk, Display

fontauthor: Caroline Hadilaksono, Micah Rich, Tyler Finck, Matt Bailey
fontyear: 2011

heroletter: Aa
heroword: Lenoidas
herostyle:

