title: Libertinus Serif
url: https://github.com/alerque/libertinus

tags: Serif, Garalde

comment: "Libertinus is the succesor to Linux Liberine from the TeX Gyre collection."

fontauthor: Philipp H. Poll
fontyear: 2025

heroletter: Ls
heroword: Liberal
herostyle: italic
color: sienna
