title: Source Serif
url: https://adobe-fonts.github.io/source-serif/

tags: Serif, Humanist

comment:

fontauthor: Frank Grießhammer
fontyear: 2014

heroletter: Aa
heroword: Creek
herostyle:
color: firebrick
