title: Source Serif
url: https://adobe-fonts.github.io/source-serif/
wikipedia: "https://de.wikipedia.org/wiki/Source_Serif"

tags: Serif, Humanist

comment:

fontauthor: Frank Grießhammer
fontyear: 2014

heroletter: Aa
heroword: Creek
herostyle:
color: firebrick

content: |
  Source Serif, entworfen von Frank Grießhammer für Adobe, ist der Serifen-Begleiter zu Source Sans und erschien 2014 als drittes Mitglied der Source-Familie. Mit humanistischen Proportionen und moderatem Strichkontrast deckt die Variableschrift optische Größen von Caption bis Display ab.
