title: Source Serif
url: https://adobe-fonts.github.io/source-serif/
wikipedia: https://en.wikipedia.org/wiki/Source_Serif

tags: Serif, Humanist

comment:

fontauthor: Frank Grießhammer
fontyear: 2014

heroletter: Aa
heroword: Creek
herostyle:
color: firebrick
