title: Epilogue
url: https://github.com/Etcetera-Type-Co/Epilogue
tags: Sans, Geometric, Display
fontauthor: Tyler Finck (Etcetera Type Co)
fontyear: 2020
heroletter: Ep
heroword: Finale

border: diagonal.svg

content: |
  Epilogue von Tyler Finck (Etcetera Type Co.) ist eine geometrische Sans-Serif-Variableschrift für kraftvolle Display-Überschriften. Ihr weiter Gewichtsbereich – von Thin bis ExtraBlack – und die klaren konstruktiven Formen machen sie zur ersten Wahl für plakativen, modernen Headline-Einsatz.
