title: Amstelvar
url: https://github.com/googlefonts/amstelvar

tags: Sans, Humanist, Neo, Grotesk

comment: "@todo"

fontauthor: The Font Bureau
fontyear: 2019

heroletter: Aa
heroword: Amsterdam
herostyle:
color: MediumAquamarine

content:
