title: Mozilla Headline
url: https://github.com/mozilla/mozilla-type-family

tags: Slab Serif, Display

comment: "Need to slab on a headline?"

fontauthor: Studio DRAMA
fontyear: 2024

heroletter: Aá
heroword: Godzilla
herostyle:
color: Coral
