title: Mozilla Headline
url: https://github.com/mozilla/mozilla-type-family

tags: Serif, Slab Serif, Display

comment: "Brauchst du eine Serifenschrift für Überschriften?"

fontauthor: Studio DRAMA
fontyear: 2024

heroletter: Aá
heroword: Godzilla
herostyle:
color: Coral

content: |
  Mozilla Headline ist der markante Slab-Serif-Bestandteil des 2024 von Studio DRAMA entworfenen Mozilla-Typsystems. Die ausdrucksstarken Serifen und der hohe Kontrast machen sie zur Wahl für dominante Überschriften in Mozillas Markenkommunikation – selbstbewusst, technisch und gleichzeitig einladend.
