title: Recursive
url: https://www.recursive.design
tags: Monospace, Sans, Variable

fontauthor: Stephen Nixon (ArrowType)
fontyear: 2020

heroletter: Rr
heroword: Variabel

color: blueviolet

content: |
  Recursive ist eine moderne Variable Font von Stephen Nixon, die speziell für die Bildschirmdarstellung konzipiert wurde. Mit fünf kontrollierbaren Achsen (Monospace, Casual, Weight, Slant, Cursive) bietet sie beispiellose Flexibilität und erlaubt subtile bis drastische gestalterische Variationen. Entwickelt für Entwickler und Designer, vereint die Schriftfamilie Funktionalität mit spielerischer Kreativität.
