title: Basteleur
url: https://velvetyne.fr/fonts/basteleur/

tags: Serif, Display, Reverse Contrast

fontauthor: Keussel
fontyear: 2021

heroletter: Bb
heroword: Buch
color: darkorchid

content: |
  Basteleur ist eine Serif mit umgekehrtem Strichkontrast, die von der Typografie des 15. Jahrhunderts und der Ästhetik früher Bitmap-Schriften inspiriert ist. Die beiden Schnitte Moonlight (leicht) und Bold bieten kontrastreiches Zeichenwerk mit einer charakteristischen, historisch geprägten Ausstrahlung. Velvetynes eigenständiger Beitrag zur Serifenlandschaft neben Compagnon und Krikikrak.
