title: Recursive
url: https://github.com/arrowtype/recursive

tags: Monospace

comment: 

fontauthor: Stephen Nixon, ⁠Arrow Type.
fontyear: 2020

heroletter: Fi
heroword: Rewrite
herostyle:
color: SandyBrown
border: hash.svg
