title: Space Grotesk
url: https://floriankarsten.github.io/space-grotesk/
tags: Sans, Geometric, Sans-Serif, Coding
fontauthor: Florian Karsten
fontyear: 2020
heroletter: Sg
heroword: Space
color: darkorange
border: dots_small.svg
