title: Space Grotesk
url: https://floriankarsten.github.io/space-grotesk/
tags: Sans, Geometric, Coding
fontauthor: Florian Karsten
fontyear: 2020
heroletter: Sg
heroword: Space
color: darkorange
border: dots_small.svg

content: |
  Space Grotesk von Florian Karsten ging aus dem vorhandenen monospaced Space Mono hervor, wurde jedoch zu einer proportionalen Schrift umgearbeitet. Das Ergebnis ist eine unverwechselbare geometrische Groteskschrift mit leicht technischem Retro-Charakter, die sich für UI-Design ebenso eignet wie für Überschriften.
