title: Public Sans
url: https://github.com/uswds/public-sans

tags: Sans, Humanist, Grotesk

comment:

fontauthor: United States Web Design System
fontyear: 2020

heroletter: US
heroword: Public
herostyle:
color: navy

content: |
  Public Sans ist eine für das US-amerikanische Web Design System (USWDS) entwickelte Groteskschrift, die auf Libre Franklin basiert. Speziell für digitale Regierungsangebote optimiert, stehen maximale Lesbarkeit, gute Zugänglichkeit und ein neutrales Erscheinungsbild im Vordergrund.
