title: Public Sans
url: https://github.com/uswds/public-sans

tags: Sans, Humanist, Grotesk

comment:

fontauthor: United States Web Design System
fontyear: 2020

heroletter: US
heroword: Public
herostyle:

