title: Public Sans
url: https://github.com/uswds/public-sans

tags: Humanist Sans, Grotesk

comment: 

fontauthor: United States Web Design System 
fontyear: 2020

heroletter: US
heroword: Public
herostyle:
color: navy
