title: PT Sans
url: https://www.paratype.com/fonts/pt/pt-sans
wikipedia: https://en.wikipedia.org/wiki/PT_Fonts
tags: Humanist, Sans-Serif
fontauthor: Alexandra Korolkova, Olga Umpeleva, Vladimir Yefimov (ParaType)
fontyear: 2009
heroletter: Pp
heroword: Простота
color: steelblue
border: lines.svg
content: |
  Teil der PT-Schriftenfamilie, entwickelt im Auftrag der russischen
  Bundesregierung. Umfangreiche Kyrillisch-Unterstützung, gut lesbar
  auf Bildschirmen. Das Pendant PT Serif teilt die gleichen Metriken.
