title: Junction
url: https://theleagueofmoveabletype.com/junction

tags: Sans, Humanist, Grotesk

fontauthor: Caroline Hadilaksono, Tyler Finck
fontyear: 2011

heroletter: Aa
heroword: Highway
herostyle:
color: peru
border: lines.svg
