title: Piazzolla
url: https://github.com/huertatipografica/piazzolla
tags: Serif, Display, Expressiv
fontauthor: Juan Pablo del Peral (Huerta Tipográfica)
fontyear: 2020
heroletter: Pz
heroword: Tango

border: doodle.svg
