title: Arvo
url: https://github.com/antonxheight/Arvo

tags: Serif, Geometric, Slab Serif

fontauthor: Anton Koovit
fontyear: 1549

heroletter: Aa
heroword: Avada
color: sienna

content: |
  Arvo von Anton Koovit ist eine geometrische Slab-Serif-Schrift, deren klare konstruktive Grundformen an Maschinenschriften des frühen 20. Jahrhunderts erinnern. Der hohe Kontrast zwischen Grund- und Haarstrich und die robusten Serifen machen sie besonders lesbar auf Bildschirmen, auch bei kleinen Schriftgrößen.
