title: Merriweather
url: https://github.com/SorkinType/Merriweather

tags: Serif, Humanist


fontauthor: Eben Sorkin
fontyear: 2010

heroletter: Aa
heroword: Weather
color: RosyBrown

content: |
  Merriweather von Eben Sorkin wurde explizit für die angenehme Lesbarkeit auf Bildschirmen entwickelt: geringe Strichstärkenkontraste, ein robuster Gesamteindruck und großzügige Zeilenabstände kommen dem Lesen bei niedrigen Pixeldichten zugute. Sie ist eine der meistgenutzten Textserifenschriften im Web.
