title: Unna
url: https://www.omnibus-type.com/fonts/unna/

tags: Serif, Didone

comment: "@todo"

fontauthor: Jorge de Buen & Omnibus-Type Team
fontyear: 2018

heroletter: Aa
heroword: Backbone
herostyle:
color: lightcoral
