title: Cascadia Code
url: https://github.com/microsoft/cascadia-code
tags: Monospace, Coding, Ligaturen
fontauthor: Microsoft
fontyear: 2019
heroletter: Cc
heroword: Code

border: hash.svg
wikipedia: "https://en.wikipedia.org/wiki/Cascadia_Code"
