title: Epilogue
url: https://github.com/Etcetera-Type-Co/Epilogue
tags: Sans, Geometric, Display
fontauthor: Tyler Finck (Etcetera Type Co)
fontyear: 2020
heroletter: Ep
heroword: Finale

border: diagonal.svg
