title: Epilogue
url: https://github.com/Etcetera-Type-Co/Epilogue
tags: Sans, Geometric, Sans-Serif, Display
fontauthor: Tyler Finck (Etcetera Type Co)
fontyear: 2020
heroletter: Ep
heroword: Finale
color: midnightblue
border: diagonal.svg
content: |
  Moderne geometrische Grotesk mit großem x-Höhe und markanten Details.
  Variable Font. Inspiriert von frühen geometrischen Grotesken der 1920er,
  mit zeitgemäßen optischen Korrekturen.
