title: Maple Mono
url: https://github.com/subframe7536/maple-font
comment: "Ich versuche, mich mit ihr anzufreunden."
favorite: true

tags: Monospace, Coding

fontauthor: subframe7536
fontyear:

heroletter: Aa
heroword: Hardware

herostyle:

border: hash.svg

content: |
  Maple Mono ist eine von subframe7536 entwickelte Programmierschrift mit abgerundeten Ecken und optionalen Ligatursets, die ihr einen freundlicheren Charakter als viele klassische Coding-Fonts geben. Entstanden im chinesischsprachigen Open-Source-Umfeld, bringt sie zudem umfangreiche Unterstützung für CJK-Zeichen mit.
