title: Maple Mono
url: https://github.com/subframe7536/maple-font
comment: "Ich versuche, mich mit ihr anzufreunden."

tags: Monospace, Coding

fontauthor: subframe7536
fontyear:

heroletter: Aa
heroword: Hardware

herostyle:

border: hash.svg
