title: Maple Mono
url: https://github.com/subframe7536/maple-font
comment: "I am tying to befriend it."

tags: Monospace, Coding

fontauthor: subframe7536
fontyear:

heroletter: Aa
heroword: Hardware

herostyle:
color: PaleGreen
border: hash.svg
