title: Roslindale
url: https://fonts.google.com/specimen/Roslindale

tags: Serif, Display, Optical Sizes

fontauthor: David Jonathan Ross
fontyear: 2019

heroletter: Rr
heroword: "Roslindale"
color: darkred

content: |
  Roslindale von David Jonathan Ross ist eine Display-Serif-Familie mit optischer Größenachse, die von klassischen De Vinne-Schriften des 19. Jahrhunderts inspiriert ist. In großen Graden zeigt sie ausgeprägte Strichstärkenkontraste und dekorative Details; kleinere Größen nutzen die optische Achse für ausgewogene Lesbarkeit. Stilistisch zwischen historischer Referenz und zeitgemäßem Editorial-Design.
