title: IBM Plex Serif
url: https://github.com/IBM/plex

tags: Serif, Humanist

comment: "I like the IBM Plex fonts a lot. They nail the classic look and are easy to read. Sprinkled with a bit of \"tech feel\""

fontauthor: Mike Abbink, Paul van der Laan, Pieter van Rosmalen
fontyear: 2017

heroletter: Aa
heroword: Technology
herostyle:
color: darkblue
