title: IBM Plex Serif
url: https://github.com/IBM/plex
wikipedia: https://en.wikipedia.org/wiki/IBM_Plex

tags: Serif, Humanist

comment: 'Ich mag die IBM-Plex-Schriften sehr. Sie treffen den klassischen Look und sind gut lesbar – mit einem Hauch von „Tech-Feeling".'

fontauthor: Mike Abbink, Paul van der Laan, Pieter van Rosmalen
fontyear: 2017

heroletter: Aa
heroword: Technology
herostyle:
color: SteelBlue
