title: DINish
url: https://github.com/playbeing/dinish
wikipedia: "https://de.wikipedia.org/wiki/DIN_1451"

tags: Sans, Grotesk, Neo

fontauthor: Bert Driehuis, Stefan Peev, Altinn, Datto Inc.
fontyear: 2023

heroletter: Aa
heroword: Autobahn
herostyle:

border: lines.svg