title: Literata
url: https://github.com/googlefonts/literata
wikipedia: https://en.wikipedia.org/wiki/Literata

tags: Serif, Humanist

comment: "Ich kannte sie nicht, bevor ich über Teuderun gestolpert bin – und ich mag sie sehr."

fontauthor: Veronika Burian, José Scaglione
fontyear: 2017

heroletter: Au
heroword: Practical
herostyle: italic
