title: Literata
url: https://github.com/googlefonts/literata
wikipedia: https://en.wikipedia.org/wiki/Literata

tags: Serif, Humanist

comment: "I didn't know of it before I stumbled across Teuderun and I like it a lot."

fontauthor: Veronika Burian, José Scaglione
fontyear: 2017

heroletter: Au
heroword: Practical
herostyle: italic
color: olivedrab