title: Literata
url: https://github.com/googlefonts/literata
wikipedia: https://en.wikipedia.org/wiki/Literata

tags: Serif, Humanist

comment: "Ich kannte sie nicht, bevor ich über Teuderun gestolpert bin – und ich mag sie sehr."

fontauthor: Veronika Burian, José Scaglione
fontyear: 2017

heroletter: Au
heroword: Practical
herostyle: italic
color: olivedrab
content: |
  Literata wurde von TypeTogether für Google Play Books entwickelt und ist auf das angenehme Lesen langer Texte auf digitalen Displays ausgelegt. Die humanistische Serifenschrift mit abgestimmten optischen Größen wurde besonders für E-Book-Leser und Tablets konzipiert.
