title: Cooper Hewitt
url: https://github.com/cooperhewitt/CooperHewitt-Font
wikipedia: "https://en.wikipedia.org/wiki/Cooper_Hewitt,_Smithsonian_Design_Museum"

tags: Sans, Grotesk

fontauthor: Chester Jenkins (Village)
fontyear: 2014

license: "SIL Open Font License 1.1"

heroletter: Aa
heroword: Design
herostyle:

content: |
  Cooper Hewitt wurde von Chester Jenkins (Village) im Auftrag des Cooper Hewitt, Smithsonian Design Museum in New York als frei nutzbare Hausschrift entwickelt. Die grotesque Sans-Serif verbindet klare, funktionale Formen mit einem eigenständigen Charakter und wurde bewusst unter offener Lizenz veröffentlicht, damit auch andere Institutionen sie einsetzen können.
