title: Libre Baskerville
url: https://github.com/impallari/Libre-Baskerville

tags: Serif, Garalde

fontauthor: Pablo Impallari, Rodrigo Fuenzalida
fontyear: 2015

heroletter: Aa
heroword: Baskerville
herostyle:
color: darkred
border: floral.svg
