title: Libre Baskerville
url: https://github.com/impallari/Libre-Baskerville
wikipedia: "https://de.wikipedia.org/wiki/Baskerville_(Schriftart)"

tags: Serif, Garalde, Transitional

fontauthor: Pablo Impallari, Rodrigo Fuenzalida
fontyear: 2015

heroletter: Aa
heroword: Baskerville
herostyle:

border: floral.svg

content: |
  Libre Baskerville von Pablo Impallari ist ein Revival der Transitional-Serifenschrift, die John Baskerville um 1757 in Birmingham entwarf. Baskervilles Innovation war die Verbindung von hohem Strichkontrast mit klaren, regelmäßigen Formen – ein Übergang zwischen den humanistischen Garalde-Schriften und den späteren Didone-Stilen.
