title: Fancy


content: |
  The _only_ appropriate use of "Comic Sans" according to [Comic Sans Criminal](https://comicsanscriminal.com/):

  > * Your audience is under 11 years old
  > * You're designing a comic
  > * Your audience is dyslexic and has stated that they prefer comic sans