title: Libertinus Sans
url: https://github.com/alerque/libertinus
wikipedia: "https://de.wikipedia.org/wiki/Linux_Libertine"

tags: Sans, Humanist

fontauthor: Philipp H. Poll
fontyear: 2025

heroletter: Ls
heroword: Seismic
herostyle: italic

