title: Libertinus Sans
url: https://github.com/alerque/libertinus
wikipedia: https://en.wikipedia.org/wiki/Libertinus

tags: Humanist Sans, Humanist

fontauthor: Philipp H. Poll
fontyear: 2025

heroletter: Ls
heroword: Seismic
herostyle: italic
color: darkgoldenrod
