title: Libertinus Sans
url: https://github.com/alerque/libertinus
wikipedia: "https://de.wikipedia.org/wiki/Linux_Libertine"

tags: Sans, Humanist

fontauthor: Philipp H. Poll
fontyear: 2025

heroletter: Ls
heroword: Seismic
herostyle: italic
color: darkgoldenrod

content: |
  Libertinus Sans ist der Sans-Serif-Begleiter zur Libertinus Serif und teilt mit ihr die humanistischen Proportionen und den klassischen Charakter. Das gesamte Libertinus-Projekt ist aus Linux Libertine hervorgegangen und wird als vollständig Unicode-konforme freie Schrift für wissenschaftliche und buchgestalterische Zwecke gepflegt.
