title: EB Garamond
url: https://googlefonts.github.io/ebgaramond-specimen
wikipedia: "https://de.wikipedia.org/wiki/Garamond_(Schriftart)"
favorite: true

tags: Serif, Garalde, Humanist

fontauthor: Georg Duffner, Octavio Pardo
fontyear: 2011

heroletter: Ga
heroword: Garden
herostyle: bold

border: floral.svg


content: |
  EB Garamond ist Georg Duffners digitales Revival der Garamond-Originalschriften des 16. Jahrhunderts, basierend auf historischen Druckbuch-Reproduktionen. Die Schrift folgt dem Egenolff-Berner-Musterbuch von 1592 und versucht, den authentischen Duktus der frühneuzeitlichen Buchdruckerschrift zu rekonstruieren.
