title: Libre Franklin
url: https://github.com/impallari/Libre-Franklin

tags: Sans, Grotesk, Variable

fontauthor: Impallari Type, Pentagram, Google Fonts
fontyear: 2016

heroletter: Lf
heroword: Franklin
herostyle: bold
color: firebrick

content: |
  Libre Franklin ist eine offene Neuinterpretation der Franklin Gothic, die 1902 von Morris Fuller Benton für American Type Founders entworfen wurde. Pentagram und Impallari Type entwickelten die Neuauflage für Google Fonts mit neun Schnitten von Thin bis Black, jeweils in Kursive, sowie als Variable Font mit stufenloser Gewichtsachse.
