title: Libre Caslon
url: https://github.com/impallari/Libre-Caslon-Text
wikipedia: "https://de.wikipedia.org/wiki/Caslon"
comment: "Caslon-Klon, speziell für Fließtext im Web optimiert."

tags: Serif, Garalde, Old Style

fontauthor: Christian Thalmann
fontyear: 2015

heroletter: Aá
heroword: Chaffeur Acteon
herostyle:
color: SeaGreen
border: floral.svg

content: |
  Libre Caslon ist eine für den Fließtext im Web optimierte Adaption der Caslon-Schriften, die William Caslon I. im frühen 18. Jahrhundert in London entwarf. Caslons warmherzige, leicht unregelmäßige Formen wurden für digitale Lesbarkeit angepasst, ohne ihren historischen Charakter zu verlieren.
