title: Libre Caslon
url: https://github.com/impallari/Libre-Caslon-Text
comment: "Caslon clone specifically optimized for web body text"

tags: Serif, Garalde, Old Style

fontauthor: Christian Thalmann
fontyear: 2015

heroletter: Aá
heroword: Chaffeur Acteon
herostyle:
color: SeaGreen
border: floral.svg
