title: Libre Caslon
url: https://github.com/impallari/Libre-Caslon-Text
wikipedia: "https://de.wikipedia.org/wiki/Caslon"
comment: "Caslon-Klon, speziell für Fließtext im Web optimiert."

tags: Serif, Garalde, Old Style

fontauthor: Christian Thalmann
fontyear: 2015

heroletter: Aá
heroword: Chaffeur Acteon
herostyle:

border: floral.svg
