title: Zilla Slab
url: https://github.com/mozilla/zilla-slab

tags: Serif, Slab Serif, Clarendon

fontauthor: Typotheque (Peter Bilak, Nikola Djurek)
fontyear: 2017

heroletter: Zz
heroword: "Typeface"
color: brown

content: |
  Zilla Slab entstand als Eigenmarken-Familie für Firefox und kombiniert großzügige Slab-Serifen mit moderaten Kontrasten – eine zeitgenössische Interpretation des Clarendon-Stils. Die fünf Gewichte von Light bis Bold und ihre Kursiv-Varianten bieten ausreichend Flexibilität für Print- und Webprodukte. Als stabile Schrift für Überschriften und kurze Textblöcke ergänzt sie perfekt ihre Schwesterfonts Mozilla Text und Mozilla Headline.
