title: Cormorant
url: https://github.com/CatharsisFonts/Cormorant

tags: Serif, Garalde, Display

fontauthor: Christian Thalmann
fontyear: 2015

heroletter: Aá
heroword: Chaffeur Acteon
herostyle:
color: saddlebrown

