title: Newsreader
url: https://github.com/productiontype/Newsreader
tags: Serif, Transitional, Newspaper
fontauthor: Production Type
fontyear: 2020
heroletter: Nn
heroword: News
color: navy
border: lines.svg


content: |
  Newsreader von Production Type ist eine hochkontrastreiche Transitional-Serifenschrift für den digitalen Zeitungsdruck und Online-Publishing. Drei optische Größen (Caption, Text, Display) erlauben eine fein abgestimmte Typografie, die sowohl für Mengentexte als auch für markante Überschriften funktioniert.
