title: JetBrains Mono
url: https://github.com/JetBrains/JetBrainsMono
wikipedia: "https://en.wikipedia.org/wiki/JetBrains"

tags: Monospace, Coding

comment: "Sie ist einfach angenehm für meine Augen."

fontauthor: JetBrains
fontyear:

heroletter: Aa
heroword: Computer

border: hash.svg
