title: JetBrains Mono
url: https://github.com/JetBrains/JetBrainsMono

tags: Humanist Sans

comment: "It is just pleasant to my eyes."

fontauthor: JetBrains
fontyear:

heroletter: Aa
heroword: Computer
color: darkslateblue
herostyle: italic
