title: Hack
url: https://github.com/source-foundry/Hack
wikipedia: https://en.wikipedia.org/wiki/Hack_(typeface)
tags: Monospace

comment: 

fontauthor: Christopher Simpkins, Source Foundry
fontyear: 2015

heroletter: Ha
heroword: Hacker
herostyle:
color: RoyalBlue
border: hash.svg

content: |
  Hack ist eine leseoptimierte Monospace-Schrift, die auf Bitstream Vera und DejaVu Sans Mono aufbaut. Christopher Simpkins überarbeitete 2015 die Formen für maximale Klarheit im Quellcode: Die Zeichen sind sorgfältig angepasst, um Verwechslungen zwischen 0/O/o oder 1/l/I zu minimieren.
