title: Junicode
url: https://github.com/psb1558/Junicode-font

tags: Old Style

comment: 

fontauthor: Peter S. Baker
fontyear: 2013

heroletter: Fi
heroword: Staff
herostyle:
color: FireBrick
border: floral.svg
