title: Junicode
url: https://github.com/psb1558/Junicode-font
wikipedia: "https://de.wikipedia.org/wiki/Junicode"

tags: Serif, Old Style

comment: 

fontauthor: Peter S. Baker
fontyear: 2013

heroletter: Fi
heroword: Staff
herostyle:

border: floral.svg

content: |
  Junicode (kurz für Junius-Unicode) wurde von Peter S. Baker speziell für die Mediävistik und historische Sprachwissenschaft entwickelt. Die Schrift bietet außergewöhnlich umfangreiche Abdeckung für Unicode-Zeichen altenglischer, mittellateinischer und runischer Schriften sowie vollständige Unterstützung für mittelalterliche Sonderzeichen.
