title: Alegreya
url: https://htfonts.com/en/fonts/alegreya-sans/

tags: Humanist Serif

comment:

fontauthor: Juan Pablo del Peral
fontyear: 2016

heroletter: Aa
heroword: Buenos
herostyle:
color: LightCoral
