title: Climate Crisis
url: https://github.com/dancoull/ClimateCrisis

tags: Display, Condensed, Variable

fontauthor: Daniel Coull
fontyear: 2022

heroletter: Cc
heroword: Schmelze
color: darkkhaki

content: |
  Climate Crisis besitzt eine ungewöhnliche Variable Achse namens YEAR – statt Gewicht oder Breite variiert die Achse zwischen 1979 und 2050, und die Letterformen erodieren visuell wie das arktische Meereis mit dem Fortschreiten des Jahres. Das Projekt visualisiert damit den Klimawandel typographisch, indem die Schrift buchstäblich zerfällt, je weiter die Jahre voranschreiten. Dies ist die einzige Variable Achse dieser Art in der gesamten Sammlung.
