title: Routed Gothic
url: https://webonastick.com/fonts/routed-gothic/

tags: Sans, Grotesk, Display

fontauthor: Darren Embry
fontyear: 2021

heroletter: Rr
heroword: "ROUTE 66"
color: darkslategray

content: |
  Routed Gothic ist eine digitale Nachzeichnung der Schablonenschrift aus amerikanischen Industrie- und Ingenieurzeichnungen des 20. Jahrhunderts. Darren Embry rekonstruierte sie aus historischen Quellen und veröffentlichte sie als vollständige Schriftfamilie mit mehreren Gewichten und Breiten. Der einzigartige, technisch-historische Charakter hat kein Pendant im aktuellen Bestand.
