
title: Komika
url: https://www.1001fonts.com/komika-font.html

comment:

tags: Script

fontauthor: Apostrophic Labs
fontyear: 2009

heroletter: Ma
heroword: Pow!
herostyle:

border: doodle.svg

content: |
  Komika imitiert die handgezeichnete Beschriftung amerikanischer Comic-Hefte aus der Mitte des 20. Jahrhunderts. Die fetten, leicht ungleichmäßigen Formen von Apostrophic Labs erzeugen das typische gezeichnete Gefühl von Sprechblasen und Soundeffekten.
