title: Sorts Mill Goudy
url: https://fonts.google.com/specimen/Sorts+Mill+Goudy

tags: Serif, Garalde, Old Style

fontauthor: Barry Schwartz (revival)
fontyear: 2010

heroletter: Gg
heroword: "Goudy"
color: goldenrod

content: |
  Sorts Mill Goudy ist eine freie digitale Rekonstruktion von Frederic W. Goudys klassischem Goudy Old Style, überarbeitet von Barry Schwartz für den Einsatz in modernen Drucksystemen. Als unterschätzter Old-Style-Serif ergänzt er EB Garamond um eine fundamental andere historische Referenz — den amerikanischen Schriftbauer des frühen 20. Jahrhunderts.
