title: Great Vibes
url: https://github.com/googlefonts/great-vibes

tags: Script, Kalligraphisch, Display

fontauthor: Rob Leuschke (TypeSETit)
fontyear: 2012

heroletter: Gg
heroword: "Grace"
color: mediumorchid

content: |
  Great Vibes ist eine formale Kupferstich-Schrift mit klassischem Schwung und eleganten, ausgeprägten Schwüngen. Die großzügigen Schnörkel und die handwerkliche Formensprache verleihen ihr eine zeitlose Qualität zwischen historischem Schreibstil und modernem Logodesign. Sie bietet einen eleganten Kontrast zu den lockeren Handschriften und informellen Skriptschriften in diesem Bestand.
