title: EB Garamond
url: https://googlefonts.github.io/ebgaramond-specimen
wikipedia: https://en.wikipedia.org/wiki/Garamond

tags: Garalde, Humanist

fontauthor: Georg Duffner, Octavio Pardo
fontyear: 2011

heroletter: Ga
heroword: Garden
herostyle: bold
color: olivedrab
border: floral.svg

