title: Fraunces
url: https://github.com/undercasetype/Fraunces
tags: Serif, Display, Optical Sizes
fontauthor: Undercase Type (Phaedra Charles, Flavia Zimbardi)
fontyear: 2020
heroletter: Ff
heroword: Wonky
color: goldenrod
border: floral.svg
