title: Barlow
url: https://fonts.google.com/specimen/Barlow

tags: Sans, Condensed, Grotesk

fontauthor: Jeremy Tribby
fontyear: 2017

heroletter: Bb
heroword: "Barlow"
color: darkcyan

content: |
  Barlow von Jeremy Tribby ist eine umfangreiche Grotesk-Schriftfamilie mit neun Breiten von SemiCondensed bis Condensed und neun Gewichten. Inspiriert von kalifornischen Highway-Schildern und öffentlicher Beschilderung, vereint sie technische Klarheit mit einem leicht rauen, industriellen Charakter. Beliebt für sachliche Display-Typografie und als UI-Schrift.
