title: Playwrite
url: https://github.com/TypeTogether/Playwrite

comment: "Rein aus sentimentalen Gründen."

tags: Script

fontauthor: Veronika Burian, José Scaglione
fontyear: 2023

heroletter: Hi
heroword: Hello
herostyle:
color: turquoise

content: |
  Playwrite DE-LA ist Teil der globalen Playwrite-Initiative von TypeTogether und bildet die deutsche verbundene Ausgangsschrift nach. Die Schrift orientiert sich an den Schreibschrift-Standards deutschsprachiger Schulen und eignet sich für Projekte, bei denen eine authentische Handschrift-Anmutung gefragt ist.
