title: Tex Gyre Heros
url: https://www.gust.org.pl/projects/e-foundry/tex-gyre
wikipedia: "https://de.wikipedia.org/wiki/Helvetica_(Schriftart)"

tags: Sans, Neo-Grotesk

comment: "TeX Gyre Heros kann als Ersatz für die beliebte Schrift Helvetica (auch bekannt als Swiss) verwendet werden, die 1957 von Max Miedinger und Eduard Hoffmann bei der Haas Type Foundry entworfen wurde."

fontauthor: Bogusław Jackowski, Janusz M. Nowacki, Piotr Strzelczyk
fontyear: 2006

heroletter: Aa
heroword: Swiss Cheese
herostyle:


imageOverrides:
  "use_of_helvetica.png":
    alt: "Famous Brands that Uses Helvetica"
    source: "https://www.graphicpear.com/blog/famous-brands-uses-helvetica/"
