module.exports = [
  { key: "ascii", label: "Basic ASCII", short: "ASCII", range: [33, 126] },
  {
    key: "ligatures",
    label: "Ligatures",
    short: "Lig.",
    range: [64256, 64263],
  },
  { key: "fractions", label: "Fractions", short: "Frac.", range: [8528, 8544] },
  // {
  //   key: "punctuationTypo",
  //   label: "Typografische Satzzeichen",
  //   short: "Satzz.",
  //   range: [8208, 8287],
  // },
  // { key: "superSub",        label: "Hoch- / Tiefgestellt",      short: "H/T",      range: [8304,  8352]  },
  // { key: "letterlike",      label: "Buchstabenartige Symbole",  short: "Buchst.",  range: [8448,  8528]  },
  // { key: "currency",        label: "Währung",                   short: "Währ.",    range: [8352,  8400]  },
  { key: "latin1", label: "Latin-1", short: "Latin-1", range: [160, 255] },
  {
    key: "latinExtA",
    label: "Latein Erweitert-A",
    short: "Lat-A",
    range: [256, 384],
  },
  {
    key: "latinExtB",
    label: "Latein Erweitert-B",
    short: "Lat-B",
    range: [384, 592],
  },
  // {
  //   key: "latinExtAdd",
  //   label: "Latein Erweitert Zusatz",
  //   short: "Lat-Zus.",
  //   range: [7680, 7936],
  // },
  // { key: "greek",           label: "Griechisch",                short: "Griech.",  range: [880,   1024]  },
  // { key: "arrows",          label: "Pfeile",                    short: "Pfeile",   range: [8592,  8704]  },
  // { key: "boxDrawing",      label: "Boxzeichnen",               short: "Box",      range: [9472,  9600]  },
];
