title: GFS Didot
url: https://greekfontsociety-gfs.gr/typefaces/19th_century
wikipedia: "https://de.wikipedia.org/wiki/Didot_(Schriftart)"
tags: Serif, Didone, Display, Transitional

fontauthor: Greek Font Society
fontyear:

heroletter: Gt
heroword: Florist
herostyle:


gallery:
  - url: "/img/landschaft.jpg"
    alt: "Eine weite Landschaft bei Sonnenuntergang"
    source: "Max Mustermann"
