title: GFS Didot
url: https://greekfontsociety-gfs.gr/typefaces/19th_century
wikipedia: https://en.wikipedia.org/wiki/Didot_(typeface)
tags: Didone, Display, Transitional

fontauthor: Greek Font Society
fontyear:

heroletter: Gt
heroword: Florist
herostyle:
color: burlywood

gallery:
  - url: "/img/landschaft.jpg"
    alt: "Eine weite Landschaft bei Sonnenuntergang"
    source: "Max Mustermann"

eleventyNavigation:
  parent: Serif
  key: GFSDidot
  family: Serif
