title: (Nicht) Comic Sans

content: |

  # (Nicht) Comic-Sans-Schriften
  Die _einzigen_ angemessenen Verwendungszwecke für „Comic Sans" laut [Comic Sans Criminal](https://comicsanscriminal.com/):

  > * Deine Zielgruppe ist unter 11 Jahre alt
  > * Du gestaltest einen Comic
  > * Deine Zielgruppe ist legastheniebetroffen und hat angegeben, Comic Sans zu bevorzugen