title: Titillum Web
url: http://nta.accademiadiurbino.it/titillium/

tags: Sans, Geometric, Grotesk, Display

comment: "Für Momente, in denen ein etwas anderer Look gefragt ist."

fontauthor: Diego Giusti, Accademia di Belle Arti di Urbino
fontyear:

heroletter: Aa
heroword: Terminal
herostyle:
color: teal

content: |
  Titillium Web entstand als akademisches Schriftprojekt an der Accademia di Belle Arti di Urbino unter der Leitung von Diego Giusti. Die geometrische Groteskschrift mit markant abgeschnittenen Kurven ist heute vor allem durch ihre Verwendung als offizielle Schrift der italienischen Regierung bekannt.
