title: Titillum Web
url: http://nta.accademiadiurbino.it/titillium/

tags: Geometric Grotesk, Display

comment: "Für Momente, in denen ein etwas anderer Look gefragt ist."

fontauthor: Diego Giusti, Accademia di Belle Arti di Urbino
fontyear:

heroletter: Aa
heroword: Terminal
herostyle:
color: teal
