title: Titillum Web
url: http://nta.accademiadiurbino.it/titillium/

tags: Geometric Grotesk, Display

comment: "For when you need a slightly different look."

fontauthor: Diego Giusti, Accademia di Belle Arti di Urbino
fontyear:

heroletter: Aa
heroword: Terminal
herostyle:
color: teal
