title: Crimson Pro
url: https://github.com/Fonthausen/CrimsonPro
tags: Serif, Garalde, Old Style
fontauthor: Jacques Le Bailly
fontyear: 2018
heroletter: Cr
heroword: Prose
color: maroon
border: line2.svg

