title: Crimson Pro
url: https://github.com/Fonthausen/CrimsonPro
tags: Serif, Garalde, Old Style
fontauthor: Jacques Le Bailly
fontyear: 2018
heroletter: Cr
heroword: Prose

border: line2.svg


content: |
  Crimson Pro von Jacques Le Bailly ist eine Neo-Humanist-Serifenschrift, die das bewährte Crimson Text in eine Variableschrift überführt. Der warme, leicht kalligrafische Charakter und der gut abgestimmte Grauwert machen sie zur bevorzugten Wahl für langen, anspruchsvollen Lesetext.
