title: Crimson Pro
url: https://github.com/Fonthausen/CrimsonPro
tags: Garalde, Old Style, Serif
fontauthor: Jacques Le Bailly
fontyear: 2018
heroletter: Cr
heroword: Prose
color: maroon
border: line2.svg
content: |
  Leserliche Old-Style-Serif im Stil der Renaissance-Druckschriften.
  Variable Font mit Gewichtsbereich 200–900. Weiterentwicklung der
  klassischen Crimson Text, mit verbesserten Kurven und mehr Gewichten.
