title: Tex Gyre Schola
url: https://www.gust.org.pl/projects/e-foundry/tex-gyre
wikipedia: "https://de.wikipedia.org/wiki/Century_(Schriftart)"

tags: Serif, Humanist

comment: "TeX Gyre Schola kann als Ersatz für Century Schoolbook verwendet werden (entworfen von Morris Fuller Benton, 1919, für die American Type Founders; ursprünglich ohne Kursiv, die erst in späteren Überarbeitungen von Linotype und ITC ergänzt wurde)."

fontauthor: Bogusław Jackowski, Janusz M. Nowacki, Piotr Strzelczyk
fontyear: 2006

heroletter: Aa
heroword: Scolar
herostyle:

