title: Overpass
url: https://github.com/RedHatOfficial/Overpass

tags: Humanist Sans, Grotesk

comment: "Open-source font inspired by Highway Gothic on american road signs."

fontauthor: Dave Crossland
fontyear: 2021

heroletter: Sf
heroword: San José
herostyle:
color: forestgreen
border: lines.svg