title: Overpass
url: https://github.com/RedHatOfficial/Overpass
wikipedia: https://en.wikipedia.org/wiki/Overpass_(typeface)

tags: Sans, Humanist Sans, Grotesk

comment: "Open-Source-Schrift, inspiriert von Highway Gothic – der Schrift auf amerikanischen Straßenschildern."

fontauthor: Dave Crossland
fontyear: 2021

heroletter: Sf
heroword: San José
herostyle:
color: forestgreen
border: lines.svg