title: Fira Sans
url: https://mozilla.github.io/Fira/

tags: Humanist Sans

comment: "Comissioned by The Mozilla Foundation and Telefonica S.A for their mobile OS. Very similar to Erik Spiekermanns \"FF Meta\"."

fontauthor: Erik Spiekermann, Ralph du Carrois
fontyear: 2013

heroletter: Fi
heroword: Meta Erik
herostyle:
color: dodgerblue
