title: Fira Sans
url: https://mozilla.github.io/Fira/
wikipedia: https://en.wikipedia.org/wiki/Fira_(typeface)

tags: Sans, Humanist Sans

comment: 'Im Auftrag der Mozilla Foundation und Telefonica S.A. für ihr mobiles Betriebssystem entwickelt. Erinnert stark an Erik Spiekermanns „FF Meta".'

fontauthor: Erik Spiekermann, Ralph du Carrois
fontyear: 2013

heroletter: Fi
heroword: Meta Erik
herostyle:
color: HotPink
border: lines.svg
