title: Cardo
url: https://fonts.google.com/specimen/Cardo

tags: Serif, Garalde, Old Style

fontauthor: David J. Perry
fontyear: 2006

heroletter: Cc
heroword: "Cardo"
color: olive

content: |
  Cardo von David J. Perry ist ein scholastischer Serif für klassische und linguistische Texte mit breiter Unicode-Abdeckung für antike Sprachen, diakritische Zeichen und Sonderschriften. Als Gegenstück zu Junicode mit anderem historischen Vorbild und anderer Proportionierung bietet er eine zweite freie Referenz für wissenschaftlichen und humanistischen Textsatz.
