title: Spectral
url: https://github.com/productiontype/Spectral
tags: Serif, Transitional, Screen
fontauthor: Production Type
fontyear: 2017
heroletter: Sp
heroword: Lesen
color: firebrick
border: line1.svg

