title: Bodoni*
url: https://github.com/indestructible-type/Bodoni
tags: Didone, High Contrast, Elegant, High Gloss
fontauthor: Owen Earl
fontyear: 1549
heroletter: Bd
heroword: VITA NUOVA
herostyle: bold

