title: Compagnon
url: https://compagnon.eesab.fr/
comment:

tags: Serif, Slab Serif

fontauthor: Juliette Duhe, Lea Pradine
fontyear: 2010

heroletter: Aa
heroword: Champagne
herostyle:
color: maroon

