title: Krikikrak
url: https://www.carrois.com/typefaces/retail/Krikikrak/

tags: Script, Display

comment: "Wer an Comic Sans denkt – warum nicht gleich das innere Kind voll ausleben und Krikikrak verwenden?"

fontauthor: Jenny du Carrois
fontyear:

heroletter: Aa
heroword: Paperplane
herostyle:
color: coral
border: doodle.svg
