title: Krikikrak
url: https://www.carrois.com/typefaces/retail/Krikikrak/

tags: Script, Display

comment: "Wer an Comic Sans denkt – warum nicht gleich das innere Kind voll ausleben und Krikikrak verwenden?"

fontauthor: Jenny du Carrois
fontyear:

heroletter: Aa
heroword: Paperplane
herostyle:

border: doodle.svg

content: |
  Krikikrak von Jenny du Carrois (Carrois Type Design) ist eine übermütige Handschriftenschrift, die mit kindlicher Energie und geschwungenen Linien spielt. Die lockere, unregelmäßige Form macht sie ideal für kreative Projekte, bei denen Spontaneität und Lebendigkeit im Vordergrund stehen.
