title: IBM Plex Sans
url: https://github.com/IBM/plex

tags: Humanist Sans, Neo-Grotesk

comment: "The IBM Plex font family is just a nice and very readable font."

fontauthor: 	Mike Abbink, Paul van der Laan, Pieter van Rosmalen
fontyear: 2017

heroletter: Aa
heroword: Mainframe
herostyle:
color: midnightblue
