title: IBM Plex Sans
url: https://github.com/IBM/plex
wikipedia: https://en.wikipedia.org/wiki/IBM_Plex

tags: Humanist Sans, Neo-Grotesk

comment: "Die IBM-Plex-Schriftfamilie ist schlicht schön und sehr gut lesbar."

fontauthor: 	Mike Abbink, Paul van der Laan, Pieter van Rosmalen
fontyear: 2017

heroletter: Aa
heroword: Mainframe
herostyle:
color: midnightblue
