title: Mixal
url: http://www.adrienmidzic.fr

tags: Display, Variable

fontauthor: Adrien Midzic
fontyear: 2018

license: SIL Open Font License 1.0

heroletter: Mx
heroword: Mixal
herostyle: bold
color: crimson

content: |
  Mixal ist eine experimentelle Display-Schrift von Adrien Midzic mit einer Gewichtsachse von Thin bis Black. Die reduzierten, kantigen Formen sind auf plakative Wirkung in großen Schriftgrößen ausgelegt.
