title: Iosevka
url: https://github.com/be5invis/iosevka

tags: Monospace

comment: 

fontauthor: Erik Spiekermann, Ralph du Carrois
fontyear: 2013

heroletter: Fi
heroword: Meta Erik
herostyle:
color: dodgerblue
border: lines.svg
