
title: Komika
url: https://www.1001fonts.com/komika-font.html

comment:

tags: Script

fontauthor: Apostrophic Labs
fontyear: 2009

heroletter: Ma
heroword: Pow!
herostyle:
color: darkgreen
border: doodle.svg
