title: Grenze
selectedFontFolder: "Grenze"
url: https://www.omnibus-type.com/fonts/grenze/
tags: Blackletter, Serif, Slab, Display
fontauthor: Renata Polastri & Omnibus-Type Team
fontyear: 2020
heroletter: Aa
heroword: Gothic
herostyle:

