title: Cabin
url: https://github.com/googlefonts/CabinFont
tags: Humanist, Sans-Serif
fontauthor: Impallari Type
fontyear: 2010
heroletter: Ca
heroword: Cabin
color: forestgreen
border: lines.svg
content: |
  Humanistische Sans-Serif mit geometrischen Einflüssen. Variable Font
  mit Gewichts- und Breiten-Achse. Gut lesbar für Fließtext und UI.
