title: Kalam
url: https://fonts.google.com/specimen/Kalam

tags: Script

comment: "Bloß nicht verwenden. Sie könnte das neue Comic Sans werden ;-)"

fontauthor: Indian Type Foundry
fontyear: 2014

heroletter: Aá
heroword: Comics
herostyle:
color: sandybrown
border: doodle.svg
content: |
  Kalam wurde von der Indian Type Foundry als informelle Handschriftenschrift entwickelt und wirkt wie schnell hingekritzelter Text auf Papier. Der unregelmäßige Duktus, der an Kugelschreibernotizen erinnert, vermittelt bewusst Persönlichkeit und Unmittelbarkeit – und legt die Messlatte für "bitte nicht bei ernsthaften Projekten verwenden" entsprechend hoch.
