title: Kalam
url: https://fonts.google.com/specimen/Kalam

tags: Script

comment: "Don' use it. It might become the new Comic Sans ;-)"

fontauthor: Indian Type Foundry
fontyear: 2014

heroletter: Aá
heroword: Comics
herostyle:
color: sandybrown
border: doodle.svg