title: DM Sans
url: https://fonts.google.com/specimen/DM+Sans

tags: Sans, Geometric, Grotesk

fontauthor: Colophon Foundry
fontyear: 2019

heroletter: Dm
heroword: "DM Sans"
color: dimgray

content: |
  DM Sans (Digital Modus Sans) vom Colophon Foundry ist ein kontrastarmer geometrischer Grotesque für kleine Schriftgrößen in digitalen Produkten. Die niedrige Strichstärkenvariation und großzügige x-Höhe machen sie robust für UI-Einsatz. Als Variable Font mit optischer Größenachse seit Version 2. Beliebt in Start-up- und Produkt-Interfaces.
