title: Inter
url: https://rsms.me/inter/
wikipedia: https://en.wikipedia.org/wiki/Inter_(typeface)

tags: Sans, Neo, Grotesk

comment: 'Wie es die Webseite sagt: „Der Standard des 21. Jahrhunderts". Sogar die URL ist schön.'

fontauthor: Rasmus Andersson
fontyear: 2017

heroletter: Aá
heroword: "Airport"
herostyle:
color: SteelBlue

content: |
  Inter wurde von Rasmus Andersson speziell für digitale Benutzeroberflächen entwickelt und seit 2017 kontinuierlich verfeinert. Ein erhöhter x-Grad, weite Gegenformen und sorgfältig kalibrierte Abstände machen sie zu einer der am weitesten verbreiteten UI-Schriften der Webära.
