title: Inter
url: https://rsms.me/inter/
wikipedia: https://en.wikipedia.org/wiki/Inter_(typeface)

tags: Neo-Grotesk

comment: "Wie es die Webseite sagt: „Der Standard des 21. Jahrhunderts". Sogar die URL ist schön."

fontauthor: Rasmus Andersson
fontyear: 2017

heroletter: Aá
heroword: "Airport"
herostyle:
color: SteelBlue
