title: Inter
url: https://rsms.me/inter/

tags: Neo-Grotesk

comment: "As the website puts it: \"The 21st century standard\". It even has a nice URL."

fontauthor: Rasmus Andersson
fontyear: 2017

heroletter: Aá
heroword: "Airport"
herostyle:
color: SteelBlue
