title: Courier Prime
url: https://quoteunquoteapps.com/courierprime/

tags: Monospace, Schreibmaschine

fontauthor: Alan Dague-Greene (Quote-Unquote Apps)
fontyear: 2013

color: saddlebrown

heroletter: Cc
heroword: Drehbuch

border: line2.svg

content: |
  Courier Prime ist die einzige klassische Schreibmaschinen-Schrift in dieser Kollektion – eine charakteristische Neugestaltung des legendären Courier speziell für Drehbuchschreiben. Mit echten Kursiven und einem gegenüber dem Original deutlich kräftigeren Fettschnitt bietet sie einen nostalgischen Kontrast zu den modernen Coding-Schriften und zeigt, wie ein historischer Klassiker zeitgenössisch neu interpretiert werden kann.
